//! The generated chat-capability suite — a pure functor from a loaded reasoner
//! graph to `{(question, expected-property)}`, plus a structural faithfulness
//! checker over the chat pipeline's [`ProcessResult`].
//!
//! Nothing in this module knows a single concept name. The corpus is the dense
//! walk `0 .. reasoner.concept_count()` over `&dyn LexicalReasoner`
//! (`probe_cases`); English + every loaded `.prx` + USC fall out of the SAME
//! loop, partitioned only by [`LexicalReasoner::ontology_of_concept`]. Every
//! `question` is realized by the grammar's frame-generator (`Frames`, in the
//! realization ontology) from typed args — the generator writes no interrogative
//! text. Every `expected` value is READ FROM THE GRAPH (a gloss from
//! `concept(id).definitions()`, an ancestor's own lemma, the derived `known`
//! set) — no expected answer string is authored here.
//!
//! `check` asserts a STRUCTURAL property over the turn's typed
//! [`ChatOutcome`], its `unresolved` set, and — for affirm/deny/gap surfaces —
//! reference strings RE-GENERATED by the realization ontology (`realize::*`),
//! never a literal answer template. In particular a turn that claims not to know
//! a KNOWN concept (`"I do not know the words cat, dog"` over a non-edge of two
//! known concepts) is scored a FALSE-NEGATION failure, not a pass — the honesty
//! core (Reiter 1978 closed-world: an abstention names only genuinely-unknown
//! surfaces).
//!
//! The witness-scale `ChatFaithfullyRealizesTheOntology` axiom carries the
//! CLEAN core (define / is-a / directional-No) over the sample graph as a
//! registered, gate-swept green sentinel; the corpus lane
//! (`praxis-corpus-tests/tests/chat_capability.rs`) runs the FULL battery
//! including the non-edge honesty class over the real corpus, where the teeth
//! (and the current red) live.

use pr4xis::logic::proof::{SimpleCounterexample, SimpleProof};
use pr4xis::ontology::Axiom;
use pr4xis::ontology::meta::OntologyName;
use pr4xis_domains::cognitive::linguistics::english::{ConceptId, English, LexicalReasoner};
/// Re-export the realization frame-generator the probe questions are realized
/// with, so downstream drivers (the corpus lane) build it identically.
pub use pr4xis_domains::cognitive::linguistics::pragmatics::realize::Frames;
use pr4xis_domains::cognitive::linguistics::pragmatics::realize::{self, ResponseContent};
use pr4xis_domains::cognitive::linguistics::pragmatics::response::ResponseFrame;
use pr4xis_domains::cognitive::linguistics::relation_lexicon::subsumption_kind;
use pr4xis_domains::formal::relations::ontology::opposition_relation_kind;
use pr4xis_domains::social::software::markup::xml::lmf::ontology::LmfPos;

use crate::{ChatOutcome, ProcessResult, process_with_reasoner};

// =========================================================================
// The generated case — (question, provenance, expected faithfulness property)
// =========================================================================

/// One generated probe: a question realized by the grammar, the exact graph
/// construct that produced it (provenance), and the faithfulness property the
/// chat's answer must carry.
pub struct ProbeCase {
    /// The question surface — realized by `Frames` from typed args, NEVER a
    /// literal in the generator.
    pub question: String,
    /// The exact edge / node the walk read to produce this case.
    pub construct: Construct,
    /// The structural property `check` asserts over the turn.
    pub expected: Expected,
}

/// The graph construct a probe was derived from — its provenance. The `source`
/// on [`Construct::Definition`] is `ontology_of_concept`, so a legal/USC case is
/// recognized as its own stratum with no source-specific code path.
pub enum Construct {
    /// A concept that carries a gloss → a "what is X" define probe.
    Definition {
        id: ConceptId,
        source: Option<OntologyName>,
    },
    /// A true is-a pair `child ⊑ ancestor` (from `ancestors`) → an affirming
    /// polar probe.
    IsAPositive {
        child: ConceptId,
        ancestor: ConceptId,
    },
    /// The REVERSE of a strict edge `child ⊑ parent` → a provable-No polar probe
    /// (`(parent, child)`; Subsumption is antisymmetric).
    IsADirectionalNo { parent: ConceptId, child: ConceptId },
    /// A seeded pair with no is-a/opposition path either way → a
    /// denies-or-abstains probe (never a false Yes, never a false vocab-gap).
    NonEdge { a: ConceptId, b: ConceptId },
    // Relational { child, parent, kind } and QualityValue { id } are NOT built:
    // Parthood/grounding positives are not enumerable through the current
    // `LexicalReasoner` surface (only `reaches`-answerable, not edge-listable),
    // and there is no quality/quantity accessor on the trait. Both are flagged in
    // the module report; a quality-bearing concept degrades to the Definition
    // class (honest — no fabricated value question).
}

impl Construct {
    /// The stratum name, for the corpus lane's per-class failure breakdown.
    pub fn class_name(&self) -> &'static str {
        match self {
            Construct::Definition { .. } => "define",
            Construct::IsAPositive { .. } => "is-a",
            Construct::IsADirectionalNo { .. } => "directional-No",
            Construct::NonEdge { .. } => "non-edge",
        }
    }
}

/// The faithfulness property to check — every value read from the graph, never
/// an authored answer string.
pub enum Expected {
    /// `Answered` and the response carries the concept's own gloss.
    ContainsGloss(String),
    /// `Answered` and the response realizes the affirmative is-a sentence
    /// "`subject` is a `target`" (the SAME precise surface production uses to
    /// answer a polar is-a question — `realize::sentence_relation(subject,
    /// target, None)`), without claiming ignorance of the target. Checking
    /// this exact sentence rather than a bare substring of `target` closes a
    /// gate-invisible hole: a long define-style response can happen to
    /// mention the target's label for an unrelated reason (e.g. inside its
    /// own gloss text) without ever asserting the is-a relation.
    Affirms { subject: String, target: String },
    /// The response realizes the negation of "`subject` is-a `object`" (the two
    /// endpoints of the reversed strict edge) — a provable No.
    DeniesDirectional { subject: String, object: String },
    /// Never a false Yes over the pair, never a claim of ignorance about the
    /// KNOWN concepts, never a known concept leaked into `unresolved`. An honest
    /// abstain (or a provable No) passes.
    DeniesOrAbstains { known: Vec<String> },
    /// The honest-abstention property alone (same predicate as
    /// [`Expected::DeniesOrAbstains`], for a seeded pair known to have no path):
    /// abstains over KNOWN entities without a false vocab-gap.
    Abstains { known: Vec<String> },
}

// =========================================================================
// The per-case structural verdict
// =========================================================================

/// The verdict of a single `check` — pass, or fail carrying the structural
/// reason (used to build the corpus lane's class/count breakdown). A local,
/// comparable verdict: the registered [`Axiom`] lifts it to a
/// [`pr4xis::logic::proof::Verdict`] at its boundary.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Verdict {
    Pass,
    Fail(String),
}

impl Verdict {
    pub fn pass() -> Self {
        Verdict::Pass
    }

    pub fn is_pass(&self) -> bool {
        matches!(self, Verdict::Pass)
    }
}

// =========================================================================
// (1) THE GENERIC GENERATOR — a pure functor `reasoner → iterator of ProbeCase`
// =========================================================================

/// Seeded, stratified, bounded sampling of the concept space — deterministic
/// run-to-run. A stride over `0..concept_count()` (spread across the id space,
/// not biased to low ids) plus per-class caps; the non-edge partner offset is
/// seeded so the pairing is reproducible and auditable.
#[derive(Debug, Clone, Copy)]
pub struct SampleBudget {
    seed: u64,
    /// Target number of concept ids to visit (the stride is `count / target`).
    target_ids: usize,
    /// Max probes emitted per class (bounds the per-turn pipeline cost).
    per_class: usize,
    /// Emit non-edge probes (the honesty class). The witness sentinel omits it
    /// (its teeth are the corpus lane); the corpus lane includes it.
    include_nonedge: bool,
    /// Emit the reverse-edge directional-No class.
    include_directional_no: bool,
    /// Restrict the define class to NOMINAL concepts. RETIRED to `false` in
    /// both lanes since the verb-definition frame + its extraction path exist
    /// (a verb concept is asked over its gerundial nominal, "what is
    /// coughing") — the witness sentinel now tests that capability instead of
    /// filtering it out. Kept as a field so a future POS slice can narrow the
    /// witness lane again while it builds its extraction half.
    nominal_definitions_only: bool,
}

impl SampleBudget {
    /// The witness sentinel budget — a full walk of the tiny sample graph (every
    /// id), the clean define/is-a/directional-No core, NO non-edge class (its
    /// teeth are the corpus lane).
    pub const fn witness(seed: u64) -> Self {
        Self {
            seed,
            target_ids: usize::MAX,
            per_class: 4096,
            include_nonedge: false,
            include_directional_no: true,
            nominal_definitions_only: false,
        }
    }

    /// The corpus-lane budget — a bounded, seeded stride over the full corpus
    /// with every class enabled (the full faithfulness battery + honesty teeth).
    pub const fn corpus(seed: u64) -> Self {
        Self {
            seed,
            target_ids: 4000,
            per_class: 1500,
            include_nonedge: true,
            include_directional_no: true,
            nominal_definitions_only: false,
        }
    }

    fn stride(&self, count: usize) -> usize {
        if self.target_ids == 0 || count <= self.target_ids {
            1
        } else {
            (count / self.target_ids).max(1)
        }
    }
}

/// splitmix64 — a deterministic seed mixer for the non-edge partner offset.
fn mix(seed: u64, x: u64) -> u64 {
    let mut z = seed.wrapping_add(x).wrapping_add(0x9E37_79B9_7F4A_7C15);
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    z ^ (z >> 31)
}

/// The label AND part of speech a concept realizes under — the POS drives the
/// slot surface (a verb concept is asked over its gerundial nominal) and the
/// determiner, so the generator authors question and Expected from the SAME
/// `(label, pos)` (the FIX-B both-halves law).
fn label_pos_of(reasoner: &dyn LexicalReasoner, id: ConceptId) -> Option<(String, LmfPos)> {
    reasoner
        .concept(id)
        .and_then(|c| c.lemmas().next().map(|s| (s.to_string(), c.pos())))
}

/// THE GENERATOR: walk `0 .. reasoner.concept_count()` once and emit a
/// `ProbeCase` per graph construct. Universe-agnostic — English ids, loaded
/// `.prx` ids and USC ids all decode through the same `concept(id)` and fall out
/// of the same loop. Pure over `&dyn LexicalReasoner`; the content is 100%
/// carried by the reasoner instance.
pub fn probe_cases<'r>(
    reasoner: &'r dyn LexicalReasoner,
    frames: &'r Frames,
    budget: SampleBudget,
) -> impl Iterator<Item = ProbeCase> + 'r {
    let count = reasoner.concept_count().value as usize;
    let stride = budget.stride(count);
    let subsumption = subsumption_kind();
    let opposition = opposition_relation_kind();

    let mut cases: Vec<ProbeCase> = Vec::new();
    let mut n_def = 0usize;
    let mut n_isa = 0usize;
    let mut n_dir = 0usize;
    let mut n_non = 0usize;

    let mut v = 0usize;
    while v < count {
        let id = ConceptId::new(v as u64);
        v += stride;

        let Some(view) = reasoner.concept(id) else {
            continue;
        };
        let Some(label) = view.lemmas().next().map(|s| s.to_string()) else {
            continue; // no lemma → no probe (honest skip)
        };

        // --- Definition: the concept's own gloss is the expected content. ---
        if n_def < budget.per_class
            && (!budget.nominal_definitions_only || view.pos() == LmfPos::Noun)
            && let Some(gloss) = view.definitions().next()
        {
            // An ADVERB has no grammatical bare-copula definitional reading
            // (neither "*what is a quickly" nor "*what is quickly" is
            // well-formed the way "what is a dog"/"what is able" are for a
            // noun/adjective) — Slice B's quoted-mention do-support frame
            // asks directly for the sense instead
            // (`.notes/chat-fix-c-build-state.md`).
            let question = if view.pos() == LmfPos::Adverb {
                frames.wh_mean(&label)
            } else {
                frames.wh_definition(&label, view.pos())
            };
            cases.push(ProbeCase {
                question,
                construct: Construct::Definition {
                    id,
                    source: reasoner.ontology_of_concept(id),
                },
                expected: Expected::ContainsGloss(gloss.to_string()),
            });
            n_def += 1;
        }

        // The surface this concept takes in a nominal slot — the SAME
        // realization the question will use, so every Expected property is
        // authored in the realizer's representation (a verb concept's slot
        // surface is its gerundial nominal).
        let slot = frames.nominal_slot(&label, view.pos());

        // --- IsA positive: every strict ancestor is a true is-a pair. ---
        if n_isa < budget.per_class {
            for anc in reasoner.ancestors(id) {
                if anc == id {
                    continue; // drop the reflexive head
                }
                let Some((anc_label, anc_pos)) = label_pos_of(reasoner, anc) else {
                    continue;
                };
                let anc_slot = frames.nominal_slot(&anc_label, anc_pos);
                cases.push(ProbeCase {
                    question: frames.polar_isa(&label, view.pos(), &anc_label, anc_pos),
                    construct: Construct::IsAPositive {
                        child: id,
                        ancestor: anc,
                    },
                    expected: Expected::Affirms {
                        subject: slot.clone(),
                        target: anc_slot,
                    },
                });
                n_isa += 1;
                if n_isa >= budget.per_class {
                    break;
                }
            }
        }

        // --- Directional-No: the REVERSE of a strict (direct) edge. ---
        if budget.include_directional_no && n_dir < budget.per_class {
            for &parent in reasoner.parents(id) {
                if parent == id {
                    continue;
                }
                let Some((parent_label, parent_pos)) = label_pos_of(reasoner, parent) else {
                    continue;
                };
                let parent_slot = frames.nominal_slot(&parent_label, parent_pos);
                cases.push(ProbeCase {
                    // Ask "is a <parent> a <child>?" — the strict edge runs the
                    // other way, so a faithful answer denies.
                    question: frames.polar_isa(&parent_label, parent_pos, &label, view.pos()),
                    construct: Construct::IsADirectionalNo { parent, child: id },
                    expected: Expected::DeniesDirectional {
                        subject: parent_slot,
                        object: slot.clone(),
                    },
                });
                n_dir += 1;
                if n_dir >= budget.per_class {
                    break;
                }
            }
        }

        // --- NonEdge: a seeded partner with no path either way. ---
        if budget.include_nonedge && n_non < budget.per_class && count > 1 {
            let offset = 1 + (mix(budget.seed, v as u64) as usize % (count - 1));
            let w = (v + offset) % count;
            let other = ConceptId::new(w as u64);
            if other != id
                && !reasoner.reaches(id, other, &subsumption)
                && !reasoner.reaches(other, id, &subsumption)
                && !reasoner.reaches(id, other, &opposition)
                && !reasoner.reaches(other, id, &opposition)
                && let Some((other_label, other_pos)) = label_pos_of(reasoner, other)
                && other_label != label
            {
                let other_slot = frames.nominal_slot(&other_label, other_pos);
                cases.push(ProbeCase {
                    question: frames.polar_isa(&label, view.pos(), &other_label, other_pos),
                    construct: Construct::NonEdge { a: id, b: other },
                    expected: Expected::DeniesOrAbstains {
                        known: vec![slot.clone(), other_slot],
                    },
                });
                n_non += 1;
            }
        }
    }

    cases.into_iter()
}

// =========================================================================
// (3) THE GENERIC FAITHFULNESS CHECKER — structural, never string-equality
// =========================================================================

/// Fold a surface to a comparison form: lowercase, every non-alphanumeric char
/// (quotes, commas, periods) → a space, whitespace collapsed. So a
/// realizer-generated reference string matches the pipeline's response modulo
/// punctuation and spacing, never demanding a byte-exact answer template.
fn normalize(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut prev_space = true;
    for ch in s.chars() {
        if ch.is_alphanumeric() {
            for c in ch.to_lowercase() {
                out.push(c);
            }
            prev_space = false;
        } else if !prev_space {
            out.push(' ');
            prev_space = true;
        }
    }
    if out.ends_with(' ') {
        out.pop();
    }
    out
}

fn contains_norm(haystack: &str, needle: &str) -> bool {
    let n = normalize(needle);
    if n.is_empty() {
        return false;
    }
    normalize(haystack).contains(&n)
}

fn answered(result: &ProcessResult) -> bool {
    matches!(result.outcome, ChatOutcome::Answered)
}

/// The realizer's OWN vocabulary-gap surface for a set of labels — the exact
/// "I do not know the word(s) …" string [`realize::realize`] emits for an
/// `UnknownVocabulary` frame naming those entities. Re-generated from the
/// realization ontology, so detecting it is structural (a frame identity), not an
/// authored answer literal.
fn realizer_gap_surface(labels: &[String]) -> String {
    let mut content = ResponseContent::new(ResponseFrame::UnknownVocabulary);
    for l in labels {
        content = content.with_entity(l);
    }
    realize::realize(&content)
}

/// Does the response claim ignorance of a KNOWN concept? — the FALSE-NEGATION
/// core. True iff the response contains the realizer's gap surface over any
/// non-empty subset of the known labels (the whole set, as the abstain branch
/// names them, or any single known label). A concept the graph KNOWS must never
/// be surfaced as an unknown word.
fn claims_ignorance_of_known(result: &ProcessResult, known: &[String]) -> bool {
    if known.is_empty() {
        return false;
    }
    // The full-set gap surface (the abstain branch names every queried entity).
    if contains_norm(&result.response, &realizer_gap_surface(known)) {
        return true;
    }
    // Any single known label surfaced as an unknown word.
    known
        .iter()
        .any(|k| contains_norm(&result.response, &realizer_gap_surface(&core_slice(k))))
}

fn core_slice(k: &str) -> Vec<String> {
    vec![k.to_owned()]
}

/// Did a KNOWN concept leak into the typed `unresolved` set? — the structural
/// mirror of the false-negation on [`ChatOutcome::Abstained`]. An abstention
/// must name only genuinely-unknown surfaces.
fn leaks_known_into_unresolved(result: &ProcessResult, known: &[String]) -> bool {
    match &result.outcome {
        ChatOutcome::Abstained { unresolved } => unresolved
            .iter()
            .any(|u| known.iter().any(|k| normalize(k) == normalize(u))),
        ChatOutcome::Answered => false,
        // A rule-governed turn never populates `unresolved` at all — the
        // structural mirror does not apply.
        ChatOutcome::Conditional { .. } | ChatOutcome::RuleResolved { .. } => false,
    }
}

/// Does the response FALSELY affirm one of the pair is-a the other? — the guard
/// that a non-edge is never answered with a fabricated Yes. Checks the
/// realizer's affirmative copula surface for both orders.
fn false_affirms_pair(result: &ProcessResult, known: &[String]) -> bool {
    if known.len() < 2 {
        return false;
    }
    let a = &known[0];
    let b = &known[1];
    let fwd = realize::sentence_relation(a, b, None);
    let rev = realize::sentence_relation(b, a, None);
    answered(result)
        && (contains_norm(&result.response, &fwd) || contains_norm(&result.response, &rev))
}

/// THE STRUCTURAL CHECKER: evaluate the expected faithfulness property against
/// the turn's typed [`ChatOutcome`], its `unresolved` set, and realizer-generated
/// reference surfaces — never a hardcoded answer.
pub fn check(result: &ProcessResult, expected: &Expected) -> Verdict {
    match expected {
        Expected::ContainsGloss(gloss) => {
            if !answered(result) {
                Verdict::Fail("define: abstained instead of answering".into())
            } else if contains_norm(&result.response, gloss) {
                Verdict::Pass
            } else {
                Verdict::Fail("define: response does not carry the concept's gloss".into())
            }
        }
        Expected::Affirms { subject, target } => {
            let affirmation = realize::sentence_relation(subject, target, None);
            if !answered(result) {
                Verdict::Fail("is-a: abstained on a true is-a edge".into())
            } else if claims_ignorance_of_known(result, core_slice(target).as_slice()) {
                Verdict::Fail("is-a: claims ignorance of a KNOWN ancestor".into())
            } else if contains_norm(&result.response, &affirmation) {
                Verdict::Pass
            } else {
                Verdict::Fail(
                    "is-a: response does not realize the affirmative is-a sentence".into(),
                )
            }
        }
        Expected::DeniesDirectional { subject, object } => {
            let neg = realize::realize_negation(subject, object, None);
            let affirm = realize::sentence_relation(subject, object, None);
            if contains_norm(&result.response, &neg) {
                Verdict::Pass
            } else if answered(result) && contains_norm(&result.response, &affirm) {
                Verdict::Fail("directional-No: FALSE Yes on the reverse of a strict edge".into())
            } else {
                Verdict::Fail("directional-No: did not realize the provable negation".into())
            }
        }
        Expected::DeniesOrAbstains { known } | Expected::Abstains { known } => {
            if false_affirms_pair(result, known) {
                Verdict::Fail("non-edge: FALSE Yes over an unrelated pair".into())
            } else if claims_ignorance_of_known(result, known) {
                Verdict::Fail("non-edge: FALSE NEGATION — claims not to know KNOWN concepts".into())
            } else if leaks_known_into_unresolved(result, known) {
                Verdict::Fail("non-edge: a KNOWN concept leaked into `unresolved`".into())
            } else {
                // Honest abstain or a provable No — both faithful.
                Verdict::Pass
            }
        }
    }
}

/// Run one probe end-to-end and check it. `lang` is the linguistic substrate
/// (tokenize / parse), `reasoner` the lexical-reasoning surface.
pub fn run_case(lang: &English, reasoner: &dyn LexicalReasoner, case: &ProbeCase) -> Verdict {
    let result = process_with_reasoner(lang, reasoner, &case.question);
    check(&result, &case.expected)
}

/// A per-class tally of failures — the corpus lane's RED breakdown.
#[derive(Debug, Default, Clone)]
pub struct FailureBreakdown {
    pub define: usize,
    pub is_a: usize,
    pub directional_no: usize,
    pub non_edge: usize,
    pub total: usize,
    /// A few example (question → reason) lines, for the panic message.
    pub examples: Vec<String>,
}

impl FailureBreakdown {
    fn record(&mut self, case: &ProbeCase, why: &str) {
        match case.construct {
            Construct::Definition { .. } => self.define += 1,
            Construct::IsAPositive { .. } => self.is_a += 1,
            Construct::IsADirectionalNo { .. } => self.directional_no += 1,
            Construct::NonEdge { .. } => self.non_edge += 1,
        }
        self.total += 1;
        if self.examples.len() < 12 {
            self.examples.push(format!(
                "[{}] {:?} — {}",
                case.construct.class_name(),
                case.question,
                why
            ));
        }
    }

    pub fn is_empty(&self) -> bool {
        self.total == 0
    }

    pub fn summary(&self) -> String {
        format!(
            "{} define, {} is-a, {} directional-No, {} non-edge (false-negation / false-Yes / gloss-miss) — {} total",
            self.define, self.is_a, self.directional_no, self.non_edge, self.total
        )
    }
}

/// Run the whole generated suite over a reasoner and collect the per-class
/// failure breakdown — the shared driver for both the witness axiom and the
/// corpus `#[test]`.
pub fn evaluate(
    lang: &English,
    reasoner: &dyn LexicalReasoner,
    frames: &Frames,
    budget: SampleBudget,
) -> FailureBreakdown {
    let mut breakdown = FailureBreakdown::default();
    for case in probe_cases(reasoner, frames, budget) {
        if let Verdict::Fail(why) = run_case(lang, reasoner, &case) {
            breakdown.record(&case, &why);
        }
    }
    breakdown
}

/// Corpus-scale counterpart to [`evaluate`] — same generation + structural
/// check, parallelized across `std::thread::available_parallelism()` worker
/// threads (the native `std::thread::scope` pattern proven in
/// `pr4xis_domains`'s `compute_defines_overlay`, no new dependency).
///
/// A production reasoner (e.g. `ComposedReasoner`) holds `Vec<Rc<
/// RuntimeOntology>>` — `Rc`, not `Sync` — so a single instance cannot be
/// shared by reference across worker threads the way [`evaluate`] shares
/// `reasoner: &dyn LexicalReasoner` in the single-threaded case. Instead the
/// caller supplies `build_reasoner`, called ONCE to generate the case list
/// (a cheap, pure structural walk over the graph — case generation itself
/// does not run the chat pipeline) and then ONCE PER WORKER THREAD (each
/// thread builds and keeps its own owned reasoner instance, never shared)
/// to run that worker's chunk of cases through the actual pipeline
/// (`run_case`), which is the expensive per-item cost this function
/// parallelizes.
///
/// Chunks are joined back in ORIGINAL chunk order — exactly like
/// `compute_defines_overlay`'s `flat_map` over its spawned handles — so the
/// assembled failure list is in the SAME order `evaluate`'s serial scan
/// would produce, regardless of thread scheduling. That determinism matters
/// beyond the per-class counts: `FailureBreakdown::record` caps `examples`
/// at the first 12 failures in scan order, so an out-of-order merge would
/// silently admit or drop different examples than the serial run. Building
/// the full ordered failure list first and only then folding it through
/// `record` (rather than recording per-chunk and merging partial
/// `FailureBreakdown`s) reproduces the serial scan's exact example list as
/// well as its exact per-class counts.
pub fn evaluate_parallel<R: LexicalReasoner>(
    lang: &English,
    build_reasoner: impl Fn() -> R + Sync + Send,
    frames: &Frames,
    budget: SampleBudget,
) -> FailureBreakdown {
    let generation_reasoner = build_reasoner();
    let cases: Vec<ProbeCase> = probe_cases(&generation_reasoner, frames, budget).collect();
    drop(generation_reasoner);

    let worker_count = std::thread::available_parallelism()
        .map(core::num::NonZeroUsize::get)
        .unwrap_or(1)
        .min(cases.len().max(1));

    let build_reasoner = &build_reasoner;
    let failures: Vec<(&ProbeCase, String)> = if worker_count <= 1 {
        run_chunk(lang, build_reasoner, &cases)
    } else {
        let chunk_size = cases.len().div_ceil(worker_count);
        std::thread::scope(|scope| {
            cases
                .chunks(chunk_size)
                .map(|chunk| scope.spawn(move || run_chunk(lang, build_reasoner, chunk)))
                .collect::<Vec<_>>()
                .into_iter()
                .flat_map(|handle| {
                    handle
                        .join()
                        .expect("evaluate_parallel worker thread panicked")
                })
                .collect()
        })
    };

    let mut breakdown = FailureBreakdown::default();
    for (case, why) in failures {
        breakdown.record(case, &why);
    }
    breakdown
}

/// One worker's unit of work for [`evaluate_parallel`]: build ONE owned
/// reasoner (never shared across threads) and run it over `chunk`'s cases in
/// order, returning only the failures — a plain `fn` (not a closure) so the
/// `&'a ProbeCase` output lifetime elides against `chunk: &'a [ProbeCase]`
/// the way closures cannot reliably infer on their own.
fn run_chunk<'a, R: LexicalReasoner>(
    lang: &English,
    build_reasoner: &(impl Fn() -> R + Sync),
    chunk: &'a [ProbeCase],
) -> Vec<(&'a ProbeCase, String)> {
    let reasoner = build_reasoner();
    chunk
        .iter()
        .filter_map(|case| match run_case(lang, &reasoner, case) {
            Verdict::Fail(why) => Some((case, why)),
            Verdict::Pass => None,
        })
        .collect()
}

// =========================================================================
// (4) THE CITED CAPABILITY AXIOM — the witness-scale green sentinel
// =========================================================================

/// A registered seed for the deterministic sampler.
const CAPABILITY_SEED: u64 = 0x1234_5678_9ABC_DEF0;

/// The witness-scale faithfulness axiom: over the sample English graph, every
/// (question, expected) the generator derives — the CLEAN core (define contains
/// the gloss, an is-a edge affirms, the reverse of a strict edge denies) — the
/// chat pipeline's realized answer carries the expected property. The non-edge
/// honesty class (whose false-negation teeth are the point) runs at CORPUS scale
/// (`praxis-corpus-tests/tests/chat_capability.rs`); here it is omitted so this
/// `constructor`-registered axiom is a GREEN sentinel swept by
/// `OntologyBaseIsConsistent`, never an `Err` on the unfixed pipeline.
pub struct ChatFaithfullyRealizesTheOntology;

impl Axiom for ChatFaithfullyRealizesTheOntology {
    fn verify(&self) -> pr4xis::logic::proof::Verdict {
        let english = English::sample_static();
        let frames = Frames::from_realization();
        // The witness graph IS the sample English substrate — the reasoner and
        // the linguistic substrate coincide (the embedded-only case).
        let breakdown = evaluate(
            english,
            english,
            &frames,
            SampleBudget::witness(CAPABILITY_SEED),
        );
        if breakdown.is_empty() {
            Ok(Box::new(SimpleProof::new(self.meta())))
        } else {
            Err(Box::new(SimpleCounterexample::new(self.meta())))
        }
    }

    pr4xis::axiom_meta!(
        "ChatFaithfullyRealizesTheOntology",
        "for every (question,expected) the generator derives from the loaded reasoner graph, the chat pipeline's realized answer carries the expected property — define contains the gloss, an is-a edge affirms, a non-edge denies-or-abstains and NEVER false-affirms, and an abstention names only genuinely-unknown surfaces (no known concept in `unresolved`)",
        "Reiter & Dale (2000) Building Natural Language Generation Systems, CUP — realization faithfulness of the generation stage; honest abstention grounded in Reiter (1978) closed-world (already cited at ChatOutcome, lib.rs:56)"
    );
}

pr4xis::register_axiom!(ChatFaithfullyRealizesTheOntology, constructor);

/// The tiny WITNESS LEXICON — a two-synset WN-LMF definitional lexicon
/// (`spaniel ⊑ hound`, surfaces deliberately disjoint from the sample
/// English graph) materialized through the SAME generic bridge every
/// registered lexicon rides
/// ([`lexicon_runtime_ontology_from_lmf`](pr4xis_domains::applied::data_provisioning::lexicon_provenance::lexicon_runtime_ontology_from_lmf)).
/// The corpus lane (`praxis-corpus-tests/tests/lexicon_chat_capability.rs`)
/// runs the same battery over the REAL registered lexicons at full-WordNet
/// scale; this witness pins the loaded-lexicon capability as a green,
/// gate-swept sentinel exactly as [`ChatFaithfullyRealizesTheOntology`]
/// pins the embedded-English core.
const WITNESS_LEXICON_LMF: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<LexicalResource>
  <Lexicon id="witness" label="Witness" language="en" email="" license="" version="1.0" url="">
    <LexicalEntry id="e-spaniel-n"><Lemma writtenForm="spaniel" partOfSpeech="n"/><Sense id="spaniel-n-01" synset="s-spaniel"/></LexicalEntry>
    <LexicalEntry id="e-hound-n"><Lemma writtenForm="hound" partOfSpeech="n"/><Sense id="hound-n-01" synset="s-hound"/></LexicalEntry>
    <Synset id="s-spaniel" ili="i100" partOfSpeech="n"><Definition>a gentle dog with long drooping ears</Definition><SynsetRelation relType="hypernym" target="s-hound"/></Synset>
    <Synset id="s-hound" ili="i101" partOfSpeech="n"><Definition>a dog bred for hunting</Definition></Synset>
  </Lexicon>
</LexicalResource>"#;

/// The witness-scale LOADED-LEXICON faithfulness axiom: over sample English
/// COMPOSED WITH the tiny witness lexicon archive (the same
/// `ComposedReasoner` union every chat host assembles), every (question,
/// expected) the generator derives — the CLEAN core (a lexicon concept's
/// define carries its gloss, its hypernym edge affirms, the reverse of its
/// strict edge denies) — the chat pipeline's realized answer carries the
/// expected property. The non-edge honesty class runs at CORPUS scale over
/// the REAL registered lexicons
/// (`praxis-corpus-tests/tests/lexicon_chat_capability.rs`); here it is
/// omitted so this `constructor`-registered axiom is a GREEN sentinel swept
/// by `OntologyBaseIsConsistent` — the `ChatFaithfullyRealizesTheOntology`
/// shape, lifted from the embedded graph to the loaded-set union.
pub struct ChatFaithfullyRealizesTheLoadedLexicons;

impl Axiom for ChatFaithfullyRealizesTheLoadedLexicons {
    fn verify(&self) -> pr4xis::logic::proof::Verdict {
        use pr4xis_domains::applied::data_provisioning::lexicon_provenance::lexicon_runtime_ontology_from_lmf;
        use pr4xis_domains::cognitive::linguistics::composed::ComposedReasoner;

        let english = English::sample_static();
        let frames = Frames::from_realization();
        let Ok(onto) = lexicon_runtime_ontology_from_lmf(
            WITNESS_LEXICON_LMF,
            OntologyName::new_static("witness_lexicon"),
        ) else {
            return Err(Box::new(SimpleCounterexample::new(self.meta())));
        };
        let composed = ComposedReasoner::new(english, vec![std::rc::Rc::new(onto)]);
        let breakdown = evaluate(
            english,
            &composed,
            &frames,
            SampleBudget::witness(CAPABILITY_SEED),
        );
        if breakdown.is_empty() {
            Ok(Box::new(SimpleProof::new(self.meta())))
        } else {
            Err(Box::new(SimpleCounterexample::new(self.meta())))
        }
    }

    pr4xis::axiom_meta!(
        "ChatFaithfullyRealizesTheLoadedLexicons",
        "for every (question,expected) the generator derives from sample English composed with a loaded witness lexicon archive, the chat pipeline's realized answer carries the expected property — a loaded lexicon concept's define contains its gloss, its hypernym edge affirms, the reverse of its strict edge denies, and an abstention names only genuinely-unknown surfaces",
        "Reiter & Dale (2000) Building Natural Language Generation Systems, CUP — realization faithfulness of the generation stage; honest abstention grounded in Reiter (1978) closed-world (already cited at ChatOutcome, lib.rs:56)"
    );
}

pr4xis::register_axiom!(ChatFaithfullyRealizesTheLoadedLexicons, constructor);

#[cfg(test)]
mod tests {
    use super::*;

    /// The witness sentinel is GREEN — the clean define/is-a/directional-No core
    /// over the sample graph is faithful. (The non-edge honesty teeth run at
    /// corpus scale.)
    #[pr4xis::praxis_value(Verifiable)]
    #[test]
    fn witness_axiom_is_green() {
        let breakdown = evaluate(
            English::sample_static(),
            English::sample_static(),
            &Frames::from_realization(),
            SampleBudget::witness(CAPABILITY_SEED),
        );
        assert!(
            breakdown.is_empty(),
            "witness sentinel must be green, got: {}\n{}",
            breakdown.summary(),
            breakdown.examples.join("\n"),
        );
        assert!(ChatFaithfullyRealizesTheOntology.verify().is_ok());
    }

    /// The loaded-lexicon witness sentinel is GREEN — the clean
    /// define/is-a/directional-No core over sample English ⊕ the witness
    /// lexicon archive is faithful. (The corpus-scale teeth over the REAL
    /// registered lexicons live in
    /// `praxis-corpus-tests/tests/lexicon_chat_capability.rs`.)
    #[pr4xis::praxis_value(Verifiable)]
    #[test]
    fn lexicon_witness_axiom_is_green() {
        use pr4xis_domains::applied::data_provisioning::lexicon_provenance::lexicon_runtime_ontology_from_lmf;
        use pr4xis_domains::cognitive::linguistics::composed::ComposedReasoner;

        let english = English::sample_static();
        let onto = lexicon_runtime_ontology_from_lmf(
            WITNESS_LEXICON_LMF,
            OntologyName::new_static("witness_lexicon"),
        )
        .expect("the witness lexicon materializes");
        let composed = ComposedReasoner::new(english, vec![std::rc::Rc::new(onto)]);
        let breakdown = evaluate(
            english,
            &composed,
            &Frames::from_realization(),
            SampleBudget::witness(CAPABILITY_SEED),
        );
        assert!(
            breakdown.is_empty(),
            "loaded-lexicon witness sentinel must be green, got: {}\n{}",
            breakdown.summary(),
            breakdown.examples.join("\n"),
        );
        assert!(ChatFaithfullyRealizesTheLoadedLexicons.verify().is_ok());
    }

    /// A `LexicalReasoner` that delegates every method to a wrapped `English`
    /// except [`conditional_rule_for_predicate`](LexicalReasoner::conditional_rule_for_predicate),
    /// which returns a fixed witness rule for one predicate — the minimal
    /// test double for the [`ChatOutcome::Conditional`] capability (no
    /// production rule-extraction producer exists yet; see task following
    /// #20).
    struct StubConditionalReasoner<'a> {
        english: &'a English,
        predicate: &'static str,
        rule: pr4xis_domains::social::judicial::conditional_rule::ConditionalRule,
    }

    impl LexicalReasoner for StubConditionalReasoner<'_> {
        fn lookup(&self, word: &str) -> &[ConceptId] {
            self.english.lookup(word)
        }
        fn concept(
            &self,
            id: ConceptId,
        ) -> Option<pr4xis_domains::cognitive::linguistics::english::ConceptView<'_>> {
            self.english.concept(id)
        }
        fn concept_by_synset(
            &self,
            synset_id: &str,
        ) -> Option<pr4xis_domains::cognitive::linguistics::english::ConceptView<'_>> {
            self.english.concept_by_synset(synset_id)
        }
        fn parents(&self, id: ConceptId) -> &[ConceptId] {
            self.english.parents(id)
        }
        fn children(&self, id: ConceptId) -> &[ConceptId] {
            self.english.children(id)
        }
        fn is_a(&self, child: ConceptId, ancestor: ConceptId) -> bool {
            self.english.is_a(child, ancestor)
        }
        fn ancestors(&self, id: ConceptId) -> Vec<ConceptId> {
            self.english.ancestors(id)
        }
        fn common_ancestor(&self, a: ConceptId, b: ConceptId) -> Option<ConceptId> {
            self.english.common_ancestor(a, b)
        }
        fn ancestor_chain(&self, child: ConceptId, ancestor: ConceptId) -> Option<Vec<ConceptId>> {
            self.english.ancestor_chain(child, ancestor)
        }
        fn concept_count(&self) -> pr4xis_domains::formal::math::quantity::value::Quantity {
            self.english.concept_count()
        }
        fn conditional_rule_for_predicate(
            &self,
            predicate: &str,
            _object: &str,
        ) -> Option<pr4xis_domains::social::judicial::conditional_rule::ConditionalRule> {
            if predicate == self.predicate {
                Some(self.rule.clone())
            } else {
                None
            }
        }
    }

    /// THE WITNESS: `ChatOutcome::Conditional` states a fully-cited rule and
    /// names the exact missing fact, over the real `process_with_reasoner`
    /// entry point (Bobrow, Kaplan, Norman, Thompson & Winograd 1977, GUS —
    /// ask, don't guess). Mirrors the `lexicon_witness_axiom_is_green`
    /// pattern: a stub reasoner overriding one method, driven through the
    /// production pipeline, never constructed by hand.
    #[pr4xis::praxis_value(Verifiable)]
    #[test]
    fn conditional_outcome_states_the_rule_and_names_the_missing_fact() {
        use pr4xis_domains::formal::meta::identifier_format::Identifier;
        use pr4xis_domains::formal::meta::source_taxonomy::ontology::SourceTaxonomyConcept;
        use pr4xis_domains::social::judicial::citation::PinpointCite;
        use pr4xis_domains::social::judicial::citation::ontology::PinpointCitationConcept;
        use pr4xis_domains::social::judicial::conditional_rule::ConditionalRule;
        use pr4xis_domains::social::judicial::ontology::{
            EvidenceRequirement, EvidenceType, LegalTerm, RequirementLevel,
        };
        use pr4xis_domains::social::judicial::source_text::SourceTextRef;

        // A hand-built LegalTerm fixture -- standing in for a future loaded
        // 42 U.S.C. § 1396p corpus entry (a real rule-extraction producer is
        // separate, unscoped follow-up work).
        let term = LegalTerm {
            id: Identifier::curie("medicaid:asset_transfer_penalty").expect("valid CURIE"),
            name: SourceTextRef::new("Medicaid asset-transfer penalty period"),
            definition: SourceTextRef::new(
                "transferring assets below fair market value within the look-back \
                 period creates a period of Medicaid home-care ineligibility",
            ),
            source_text: Some(SourceTextRef::new("42 U.S.C. § 1396p(c)(1)")),
            subsection: Some(
                PinpointCite::new().push(PinpointCitationConcept::Subsection, "(c)(1)"),
            ),
            required_evidence: vec![EvidenceRequirement {
                field: SourceTextRef::new(
                    "value and date of any asset transfers in the look-back period",
                ),
                field_type: EvidenceType::Currency,
                required: RequirementLevel::Required,
                description: Some(SourceTextRef::new("needed to compute the penalty period")),
            }],
            obligations: vec![],
            deadlines: vec![],
            rights: vec![],
            remedies: vec![],
            burdens: vec![],
            exceptions: vec![],
        };
        let rule = ConditionalRule::from_term(term, SourceTaxonomyConcept::UsFederalStatute);

        let english = English::sample_static();
        // "what is eligible" is the witness INPUT SENTENCE, empirically
        // confirmed (CLI probe) to reach `answer_question` -- but the
        // extracted predicate is "what", not "eligible": the same degenerate
        // wh-determiner parse this codebase already documents elsewhere
        // (`montague.rs`'s `n_result_composition_carries_composite_provenance`)
        // for wh+copula+adjective constructions. This witness proves the
        // ChatOutcome::Conditional WIRING end-to-end (its stated purpose);
        // recognizing "eligible for X" as a rule-governing predicate from
        // real English is the separately-flagged, unscoped predicate-
        // classification gap (design risk #1, task following #20) -- not
        // something this test claims to solve.
        let reasoner = StubConditionalReasoner {
            english,
            predicate: "what",
            rule: rule.clone(),
        };

        let result = process_with_reasoner(english, &reasoner, "what is eligible");

        match &result.outcome {
            ChatOutcome::Conditional {
                rule: got_rule,
                missing,
            } => {
                assert_eq!(got_rule.term.id.value(), "medicaid:asset_transfer_penalty");
                assert_eq!(missing.len(), 1);
                assert_eq!(
                    missing.head.requirement.field.text,
                    "value and date of any asset transfers in the look-back period"
                );
            }
            other => panic!("expected ChatOutcome::Conditional, got {other:?}"),
        }
        assert!(result.response.contains("42 U.S.C. § 1396p"));
        assert!(
            result
                .response
                .contains("value and date of any asset transfers")
        );
    }

    /// A hand-built `ConditionalRule` with ONE `Required`, `Concept`-typed
    /// evidence requirement — the ONE `EvidenceType` `ChatSession::resume`
    /// (task #17) can interpret today, resolved via the SAME
    /// `reasoner.lookup` every define/is-a turn already uses. Standing in
    /// for a future loaded corpus entry, same status as
    /// `conditional_outcome_states_the_rule_and_names_the_missing_fact`'s
    /// fixture.
    fn concept_slot_rule() -> pr4xis_domains::social::judicial::conditional_rule::ConditionalRule {
        use pr4xis_domains::formal::meta::identifier_format::Identifier;
        use pr4xis_domains::formal::meta::source_taxonomy::ontology::SourceTaxonomyConcept;
        use pr4xis_domains::social::judicial::conditional_rule::ConditionalRule;
        use pr4xis_domains::social::judicial::ontology::{
            EvidenceRequirement, EvidenceType, LegalTerm, RequirementLevel,
        };
        use pr4xis_domains::social::judicial::source_text::SourceTextRef;

        let term = LegalTerm {
            id: Identifier::curie("test:concept_slot_rule").expect("valid CURIE"),
            name: SourceTextRef::new("Test concept-gated eligibility rule"),
            definition: SourceTextRef::new("applies once you name the qualifying category"),
            source_text: Some(SourceTextRef::new("42 U.S.C. § 0000(test)")),
            subsection: None,
            required_evidence: vec![EvidenceRequirement {
                field: SourceTextRef::new("the qualifying category"),
                field_type: EvidenceType::Concept,
                required: RequirementLevel::Required,
                description: None,
            }],
            obligations: vec![],
            deadlines: vec![],
            rights: vec![],
            remedies: vec![],
            burdens: vec![],
            exceptions: vec![],
        };
        ConditionalRule::from_term(term, SourceTaxonomyConcept::UsFederalStatute)
    }

    /// THE MULTI-TURN WITNESS (task #17): turn 1 raises `Conditional` and
    /// names the missing concept; turn 2 supplies a recognized word
    /// ("dog", present in `English::sample_static`'s tiny lexicon) and the
    /// SAME session resolves the rule to `RuleResolved { applies: true }` —
    /// the Sergot et al. (1986) reduction completing across two calls to
    /// [`crate::ChatSession::ask`], never re-parsed as a fresh question.
    #[pr4xis::praxis_value(Verifiable)]
    #[test]
    fn session_fills_a_concept_slot_and_resolves_the_rule() {
        use crate::ChatSession;

        let english = English::sample_static();
        let reasoner = StubConditionalReasoner {
            english,
            predicate: "what",
            rule: concept_slot_rule(),
        };
        let mut session = ChatSession::new();

        let turn1 = session.ask(english, &reasoner, "what is eligible");
        match &turn1.outcome {
            ChatOutcome::Conditional { missing, .. } => {
                assert_eq!(
                    missing.head.requirement.field.text,
                    "the qualifying category"
                );
            }
            other => panic!("expected Conditional on turn 1, got {other:?}"),
        }
        assert!(session.is_awaiting_fact());

        let turn2 = session.ask(english, &reasoner, "dog");
        match &turn2.outcome {
            ChatOutcome::RuleResolved { rule, applies } => {
                assert!(*applies, "the sole Required element was satisfied");
                assert_eq!(rule.term.id.value(), "test:concept_slot_rule");
            }
            other => panic!("expected RuleResolved on turn 2, got {other:?}"),
        }
        assert!(!session.is_awaiting_fact());
        assert!(turn2.response.contains("42 U.S.C. § 0000(test)"));
        assert!(turn2.response.contains("applies"));
    }

    /// An UNRECOGNIZED word answering a `Concept` slot: the session must
    /// re-state the SAME prompt (never fabricate a resolution) and stay
    /// mid-turn — GUS's "ask, don't guess" applies to the resume path
    /// exactly as much as the first turn.
    #[pr4xis::praxis_value(Honest)]
    #[test]
    fn session_reasks_on_an_unrecognized_concept_answer() {
        use crate::ChatSession;

        let english = English::sample_static();
        let reasoner = StubConditionalReasoner {
            english,
            predicate: "what",
            rule: concept_slot_rule(),
        };
        let mut session = ChatSession::new();

        session.ask(english, &reasoner, "what is eligible");
        assert!(session.is_awaiting_fact());

        let turn2 = session.ask(english, &reasoner, "flurbogast");
        match &turn2.outcome {
            ChatOutcome::Conditional { missing, .. } => {
                assert_eq!(
                    missing.head.requirement.field.text,
                    "the qualifying category"
                );
            }
            other => panic!("an unresolved word must re-ask, not resolve; got {other:?}"),
        }
        assert!(
            session.is_awaiting_fact(),
            "the frame must stay open on an uninterpretable answer"
        );
    }

    /// A `Currency`-typed slot (the REAL Medicaid witness's own evidence
    /// type): the session has no cited numeral→`Quantity` grammar yet (see
    /// `ChatSession::resume`'s doc comment), so it must honestly re-ask
    /// rather than misinterpret a number as a concept or silently accept
    /// anything typed.
    #[pr4xis::praxis_value(Honest)]
    #[test]
    fn session_reasks_on_an_evidence_type_it_cannot_yet_interpret() {
        use crate::ChatSession;
        use pr4xis_domains::formal::meta::identifier_format::Identifier;
        use pr4xis_domains::formal::meta::source_taxonomy::ontology::SourceTaxonomyConcept;
        use pr4xis_domains::social::judicial::conditional_rule::ConditionalRule;
        use pr4xis_domains::social::judicial::ontology::{
            EvidenceRequirement, EvidenceType, LegalTerm, RequirementLevel,
        };
        use pr4xis_domains::social::judicial::source_text::SourceTextRef;

        let term = LegalTerm {
            id: Identifier::curie("test:currency_slot_rule").expect("valid CURIE"),
            name: SourceTextRef::new("Test currency-gated eligibility rule"),
            definition: SourceTextRef::new("applies once the asset value is known"),
            source_text: Some(SourceTextRef::new("42 U.S.C. § 0000(test)")),
            subsection: None,
            required_evidence: vec![EvidenceRequirement {
                field: SourceTextRef::new("the asset value"),
                field_type: EvidenceType::Currency,
                required: RequirementLevel::Required,
                description: None,
            }],
            obligations: vec![],
            deadlines: vec![],
            rights: vec![],
            remedies: vec![],
            burdens: vec![],
            exceptions: vec![],
        };
        let rule = ConditionalRule::from_term(term, SourceTaxonomyConcept::UsFederalStatute);

        let english = English::sample_static();
        let reasoner = StubConditionalReasoner {
            english,
            predicate: "what",
            rule,
        };
        let mut session = ChatSession::new();

        session.ask(english, &reasoner, "what is eligible");
        let turn2 = session.ask(english, &reasoner, "500 dollars");
        match &turn2.outcome {
            ChatOutcome::Conditional { missing, .. } => {
                assert_eq!(missing.head.requirement.field.text, "the asset value");
            }
            other => panic!("a Currency slot must honestly re-ask; got {other:?}"),
        }
        assert!(session.is_awaiting_fact());
    }

    /// A hand-built `ConditionalRule` with ONE `Required`, `Boolean`-typed
    /// evidence requirement — grounded against the REAL 42 U.S.C. §
    /// 1396p(c)(1)(A)/(B) text (verified on-disk, task #26): "did you (or
    /// your spouse) dispose of assets for less than fair market value on or
    /// after the look-back date". A "yes" answer SATISFIES the element
    /// (the transfer-penalty rule applies to you); a "no" answer explicitly
    /// does NOT satisfy it (the rule does not apply) — the first producer of
    /// `SlotState::NotSatisfied` anywhere in this codebase.
    fn boolean_slot_rule() -> pr4xis_domains::social::judicial::conditional_rule::ConditionalRule {
        use pr4xis_domains::formal::meta::identifier_format::Identifier;
        use pr4xis_domains::formal::meta::source_taxonomy::ontology::SourceTaxonomyConcept;
        use pr4xis_domains::social::judicial::conditional_rule::ConditionalRule;
        use pr4xis_domains::social::judicial::ontology::{
            EvidenceRequirement, EvidenceType, LegalTerm, RequirementLevel,
        };
        use pr4xis_domains::social::judicial::source_text::SourceTextRef;

        let term = LegalTerm {
            id: Identifier::curie("test:boolean_slot_rule").expect("valid CURIE"),
            name: SourceTextRef::new("Test asset-transfer disqualification rule"),
            definition: SourceTextRef::new(
                "a disqualifying transfer creates a period of ineligibility",
            ),
            source_text: Some(SourceTextRef::new("42 U.S.C. § 0000(test)")),
            subsection: None,
            required_evidence: vec![EvidenceRequirement {
                field: SourceTextRef::new(
                    "whether you disposed of assets for less than fair market value",
                ),
                field_type: EvidenceType::Boolean,
                required: RequirementLevel::Required,
                description: None,
            }],
            obligations: vec![],
            deadlines: vec![],
            rights: vec![],
            remedies: vec![],
            burdens: vec![],
            exceptions: vec![],
        };
        ConditionalRule::from_term(term, SourceTaxonomyConcept::UsFederalStatute)
    }

    /// THE BOOLEAN-AFFIRMATIVE WITNESS (task #25): "yes" satisfies the sole
    /// Required Boolean element, resolving to `RuleResolved { applies: true
    /// }` — over `english_loaded()` (not the minimal `English::sample_static`
    /// fixture, which carries no function-word/interjection data), the SAME
    /// production English the CLI/wasm hosts run.
    #[pr4xis::praxis_value(Verifiable)]
    #[test]
    fn session_fills_a_boolean_slot_with_yes_and_resolves_to_applies() {
        use crate::ChatSession;
        use pr4xis_domains::cognitive::linguistics::english::english_loaded;

        let english = english_loaded();
        let reasoner = StubConditionalReasoner {
            english,
            predicate: "what",
            rule: boolean_slot_rule(),
        };
        let mut session = ChatSession::new();

        session.ask(english, &reasoner, "what is eligible");
        let turn2 = session.ask(english, &reasoner, "yes");
        match &turn2.outcome {
            ChatOutcome::RuleResolved { applies, .. } => {
                assert!(*applies, "a 'yes' answer must satisfy the Boolean element");
            }
            other => panic!("expected RuleResolved, got {other:?}"),
        }
        assert!(!session.is_awaiting_fact());
    }

    /// THE BOOLEAN-NEGATIVE WITNESS: "no" does NOT satisfy the sole Required
    /// Boolean element, resolving to `RuleResolved { applies: false }` — the
    /// first production path anywhere that reaches `Applicability::
    /// DoesNotApply` (every other capability only ever produces `Satisfied`
    /// states).
    #[pr4xis::praxis_value(Verifiable)]
    #[test]
    fn session_fills_a_boolean_slot_with_no_and_resolves_to_does_not_apply() {
        use crate::ChatSession;
        use pr4xis_domains::cognitive::linguistics::english::english_loaded;

        let english = english_loaded();
        let reasoner = StubConditionalReasoner {
            english,
            predicate: "what",
            rule: boolean_slot_rule(),
        };
        let mut session = ChatSession::new();

        session.ask(english, &reasoner, "what is eligible");
        let turn2 = session.ask(english, &reasoner, "no");
        match &turn2.outcome {
            ChatOutcome::RuleResolved { applies, .. } => {
                assert!(
                    !*applies,
                    "a 'no' answer must NOT satisfy the Boolean element"
                );
            }
            other => panic!("expected RuleResolved, got {other:?}"),
        }
        assert!(!session.is_awaiting_fact());
    }

    /// An unrecognized answer to a Boolean slot must honestly re-ask, same
    /// as the Concept case — never default to either polarity.
    #[pr4xis::praxis_value(Honest)]
    #[test]
    fn session_reasks_on_an_unrecognized_boolean_answer() {
        use crate::ChatSession;
        use pr4xis_domains::cognitive::linguistics::english::english_loaded;

        let english = english_loaded();
        let reasoner = StubConditionalReasoner {
            english,
            predicate: "what",
            rule: boolean_slot_rule(),
        };
        let mut session = ChatSession::new();

        session.ask(english, &reasoner, "what is eligible");
        let turn2 = session.ask(english, &reasoner, "maybe");
        match &turn2.outcome {
            ChatOutcome::Conditional { missing, .. } => {
                assert_eq!(
                    missing.head.requirement.field.text,
                    "whether you disposed of assets for less than fair market value"
                );
            }
            other => panic!("an unrecognized answer must re-ask, not resolve; got {other:?}"),
        }
        assert!(session.is_awaiting_fact());
    }

    /// A `LexicalReasoner` that delegates EVERY method to a wrapped
    /// `ComposedReasoner` — the real production reasoner, not a synthetic
    /// stub — except [`conditional_rule_for_predicate`](LexicalReasoner::
    /// conditional_rule_for_predicate), which records the predicate string
    /// it was called with instead of returning a rule. Proves the GRAMMAR
    /// half of task #27 (real English collapses "eligible for" into a
    /// relational predicate) independently of the STILL-unwired production
    /// `conditional_rule_for_predicate` (task #28's job).
    struct PredicateCapture<'a> {
        composed: &'a pr4xis_domains::cognitive::linguistics::composed::ComposedReasoner,
        captured: std::cell::RefCell<Vec<String>>,
    }

    impl LexicalReasoner for PredicateCapture<'_> {
        fn lookup(&self, word: &str) -> &[ConceptId] {
            self.composed.lookup(word)
        }
        fn concept(
            &self,
            id: ConceptId,
        ) -> Option<pr4xis_domains::cognitive::linguistics::english::ConceptView<'_>> {
            self.composed.concept(id)
        }
        fn concept_by_synset(
            &self,
            synset_id: &str,
        ) -> Option<pr4xis_domains::cognitive::linguistics::english::ConceptView<'_>> {
            self.composed.concept_by_synset(synset_id)
        }
        fn parents(&self, id: ConceptId) -> &[ConceptId] {
            self.composed.parents(id)
        }
        fn children(&self, id: ConceptId) -> &[ConceptId] {
            self.composed.children(id)
        }
        fn is_a(&self, child: ConceptId, ancestor: ConceptId) -> bool {
            self.composed.is_a(child, ancestor)
        }
        fn ancestors(&self, id: ConceptId) -> Vec<ConceptId> {
            self.composed.ancestors(id)
        }
        fn common_ancestor(&self, a: ConceptId, b: ConceptId) -> Option<ConceptId> {
            self.composed.common_ancestor(a, b)
        }
        fn ancestor_chain(&self, child: ConceptId, ancestor: ConceptId) -> Option<Vec<ConceptId>> {
            self.composed.ancestor_chain(child, ancestor)
        }
        fn concept_count(&self) -> pr4xis_domains::formal::math::quantity::value::Quantity {
            self.composed.concept_count()
        }
        fn max_surface_words(&self) -> usize {
            self.composed.max_surface_words()
        }
        fn lookup_case_folded(&self, word: &str) -> Vec<ConceptId> {
            self.composed.lookup_case_folded(word)
        }
        fn is_function_word(&self, word: &str) -> bool {
            self.composed.is_function_word(word)
        }
        fn relation_for_surface(
            &self,
            surface: &str,
        ) -> Option<pr4xis_runtime::ontology::ConceptRef> {
            self.composed.relation_for_surface(surface)
        }
        fn ontology_of_concept(
            &self,
            id: ConceptId,
        ) -> Option<pr4xis::ontology::meta::OntologyName> {
            self.composed.ontology_of_concept(id)
        }
        fn is_loaded_surface(&self, surface: &str) -> bool {
            self.composed.is_loaded_surface(surface)
        }
        fn conditional_rule_for_predicate(
            &self,
            predicate: &str,
            _object: &str,
        ) -> Option<pr4xis_domains::social::judicial::conditional_rule::ConditionalRule> {
            self.captured.borrow_mut().push(predicate.to_string());
            None
        }
    }

    /// THE GRAMMAR WITNESS (task #27): over the REAL production
    /// `ComposedReasoner` (no stub), a real sentence naming "eligible for"
    /// must reach `conditional_rule_for_predicate` with EXACTLY that
    /// two-word predicate — proving the multi-word collapse
    /// (`relation_for_surface("eligible for").is_some()`, wired via the new
    /// `predicate_lexicon` merged into `relation_surface_index`) correctly
    /// routes real English, independent of task #28's still-unwired
    /// production rule lookup (this reasoner always returns `None`).
    #[pr4xis::praxis_value(Verifiable)]
    #[test]
    fn real_english_collapses_eligible_for_into_the_predicate() {
        use pr4xis_domains::cognitive::linguistics::composed::ComposedReasoner;
        use pr4xis_domains::cognitive::linguistics::english::english_loaded;

        let english = english_loaded();
        let composed = ComposedReasoner::new(english, Vec::new());
        let probe = PredicateCapture {
            composed: &composed,
            captured: std::cell::RefCell::new(Vec::new()),
        };

        let _ = process_with_reasoner(english, &probe, "is a widget eligible for a benefit");
        assert!(
            probe.captured.borrow().iter().any(|p| p == "eligible for"),
            "expected \"eligible for\" among the extracted predicates, got {:?}",
            probe.captured.borrow()
        );
    }

    /// THE FULL END-TO-END WITNESS (task #28): NO stub anywhere — real
    /// English, real `ComposedReasoner`, real `predicate_lexicon`, real
    /// `conditional_rule::registry`. A real sentence naming a topic that
    /// overlaps the registry's own asset-transfer evidence text reaches
    /// `ChatOutcome::Conditional` naming the REAL 42 U.S.C. §
    /// 1396p(c)(1)(A) rule — the capability tasks #20/#23-28 built, working
    /// through the actual production reasoner for the first time.
    #[pr4xis::praxis_value(Verifiable)]
    #[test]
    fn full_production_pipeline_resolves_a_real_conditional_rule() {
        use pr4xis_domains::cognitive::linguistics::composed::ComposedReasoner;
        use pr4xis_domains::cognitive::linguistics::english::english_loaded;

        let english = english_loaded();
        let composed = ComposedReasoner::new(english, Vec::new());

        let result =
            process_with_reasoner(english, &composed, "is a widget eligible for the assets");
        match &result.outcome {
            ChatOutcome::Conditional { rule, missing } => {
                assert_eq!(
                    rule.term.id.value(),
                    "usc42:1396p_c_1_a_asset_transfer_penalty"
                );
                assert_eq!(missing.len(), 1);
            }
            other => panic!(
                "expected the real production pipeline to resolve \
                 ChatOutcome::Conditional over the real asset-transfer rule; got {other:?} \
                 (response: {:?})",
                result.response
            ),
        }
        assert!(result.response.contains("42 U.S.C. § 1396p(c)(1)(A)"));
    }

    /// The SAME real pipeline, over an UNRELATED "eligible for" question
    /// (the shape of the real 4617-question corpus's actual "eligible for
    /// X" questions — Medicare, Medicaid, TennCare general eligibility, not
    /// asset transfers) must NOT resolve to the asset-transfer rule — the
    /// registry's topic-overlap gate (task #28) doing its job, not just
    /// the grammar (task #27) alone.
    #[pr4xis::praxis_value(Honest)]
    #[test]
    fn full_production_pipeline_does_not_misattribute_an_unrelated_eligibility_question() {
        use pr4xis_domains::cognitive::linguistics::composed::ComposedReasoner;
        use pr4xis_domains::cognitive::linguistics::english::english_loaded;

        let english = english_loaded();
        let composed = ComposedReasoner::new(english, Vec::new());

        let result =
            process_with_reasoner(english, &composed, "is a widget eligible for a benefit");
        assert!(
            !matches!(result.outcome, ChatOutcome::Conditional { .. }),
            "an object sharing no vocabulary with the asset-transfer rule's own \
             evidence text must not resolve to it; got {:?}",
            result.outcome
        );
    }

    /// THE TRACK-2 END-TO-END WITNESS: the SAME real pipeline (no stub — real
    /// `english_loaded`, `ComposedReasoner`, `predicate_lexicon`, and
    /// `conditional_rule::registry`) over a natural direct-care-workforce
    /// compliance question resolves `ChatOutcome::Conditional` naming the REAL
    /// 42 C.F.R. § 441.302(a)(6) critical-incident rule and BOTH facts it needs
    /// (the federal-floor category test and the State residual). The
    /// multi-entry registry (task #28, generalized) dispatching an
    /// incident-vocabulary object to the incident rule rather than the
    /// asset-transfer rule, all the way through the production reasoner.
    #[pr4xis::praxis_value(Verifiable)]
    #[test]
    fn full_production_pipeline_resolves_the_critical_incident_rule() {
        use pr4xis_domains::cognitive::linguistics::composed::ComposedReasoner;
        use pr4xis_domains::cognitive::linguistics::english::english_loaded;

        let english = english_loaded();
        let composed = ComposedReasoner::new(english, Vec::new());

        let question = "is financial exploitation eligible for critical incident reporting";
        let result = process_with_reasoner(english, &composed, question);
        eprintln!("--- CRITICAL-INCIDENT TRANSCRIPT ---");
        eprintln!("Q: {question}");
        eprintln!("outcome: {:?}", result.outcome);
        eprintln!("response: {}", result.response);
        match &result.outcome {
            ChatOutcome::Conditional { rule, missing } => {
                assert_eq!(
                    rule.term.id.value(),
                    "cfr42:441_302_a_6_critical_incident_reporting"
                );
                assert_eq!(missing.len(), 2, "both the federal-floor and State facts");
            }
            other => panic!(
                "expected the real production pipeline to resolve \
                 ChatOutcome::Conditional over the real critical-incident rule; got {other:?} \
                 (response: {:?})",
                result.response
            ),
        }
        assert!(result.response.contains("42 C.F.R. § 441.302(a)(6)"));
    }

    /// THE TRACK-2 MULTI-TURN WITNESS: the critical-incident rule's two-slot
    /// GUS frame filled across turns through the REAL production pipeline —
    /// turn 1 raises `Conditional`, turn 2 answers the `Boolean` federal-floor
    /// test ("yes"), and the SAME session advances to the `Concept` State
    /// residual as a fresh `Conditional`, exactly the sequential slot-filling
    /// [`crate::ChatSession`] implements. (Whether the final `Concept` slot
    /// resolves in production depends on the answered State name being a loaded
    /// concept — asserted separately below only if it resolves.)
    #[pr4xis::praxis_value(Verifiable)]
    #[test]
    fn critical_incident_rule_slot_fills_across_turns() {
        use crate::ChatSession;
        use pr4xis_domains::cognitive::linguistics::composed::ComposedReasoner;
        use pr4xis_domains::cognitive::linguistics::english::english_loaded;

        let english = english_loaded();
        let composed = ComposedReasoner::new(english, Vec::new());
        let mut session = ChatSession::new();

        let turn1 = session.ask(
            english,
            &composed,
            "is financial exploitation eligible for critical incident reporting",
        );
        eprintln!("--- MULTI-TURN TRANSCRIPT ---");
        eprintln!("turn1 outcome: {:?}", turn1.outcome);
        eprintln!("turn1 response: {}", turn1.response);
        let first_field = match &turn1.outcome {
            ChatOutcome::Conditional { rule, missing } => {
                assert_eq!(
                    rule.term.id.value(),
                    "cfr42:441_302_a_6_critical_incident_reporting"
                );
                missing.head.requirement.field_type
            }
            other => panic!("expected Conditional on turn 1, got {other:?}"),
        };
        assert_eq!(
            first_field,
            pr4xis_domains::social::judicial::ontology::EvidenceType::Boolean,
            "the Boolean federal-floor test is the first slot asked"
        );
        assert!(session.is_awaiting_fact());

        let turn2 = session.ask(english, &composed, "yes");
        eprintln!("turn2 outcome: {:?}", turn2.outcome);
        eprintln!("turn2 response: {}", turn2.response);
        match &turn2.outcome {
            ChatOutcome::Conditional { rule, missing } => {
                assert_eq!(
                    rule.term.id.value(),
                    "cfr42:441_302_a_6_critical_incident_reporting"
                );
                assert_eq!(
                    missing.head.requirement.field_type,
                    pr4xis_domains::social::judicial::ontology::EvidenceType::Concept,
                    "after the Boolean is answered, the State residual is asked next"
                );
            }
            other => panic!(
                "expected the SAME session to advance to the State-residual slot; got {other:?}"
            ),
        }
        assert!(session.is_awaiting_fact(), "the Concept slot is still open");
    }

    /// The FALSE-NEGATION detector has teeth: a turn that claims ignorance of a
    /// KNOWN concept over a non-edge is scored a FAIL, and an honest abstain
    /// passes. Both constructed as [`ProcessResult`]s so the checker's structural
    /// predicate is exercised directly.
    #[pr4xis::praxis_value(Verifiable)]
    #[test]
    fn false_negation_over_known_concepts_fails() {
        use pr4xis_domains::cognitive::linguistics::pragmatics::speech_act::SpeechAct;
        use pr4xis_domains::formal::information::diagnostics::trace_functors::PipelineTrace;

        let known = vec!["cat".to_string(), "dog".to_string()];

        // The conflation bug's surface: "I do not know the words cat, dog" while
        // cat, dog are KNOWN → the realizer's own gap frame over the known set.
        let false_neg = ProcessResult {
            response: realizer_gap_surface(&known),
            user_act: SpeechAct::Question,
            system_act: SpeechAct::Assertion,
            duration_us: 0,
            token_count: 0,
            parsed: true,
            trace: PipelineTrace::default(),
            from_ontology: false,
            outcome: ChatOutcome::Abstained {
                unresolved: Vec::new(),
            },
            why: None,
            definition_provenance: None,
        };
        assert_eq!(
            check(
                &false_neg,
                &Expected::DeniesOrAbstains {
                    known: known.clone()
                }
            ),
            Verdict::Fail("non-edge: FALSE NEGATION — claims not to know KNOWN concepts".into()),
            "a false vocab-gap over known concepts must FAIL, not pass"
        );

        // An honest abstain that does NOT claim ignorance of the known pair passes.
        let honest = ProcessResult {
            response: "I cannot confirm that from what I have loaded.".into(),
            user_act: SpeechAct::Question,
            system_act: SpeechAct::Assertion,
            duration_us: 0,
            token_count: 0,
            parsed: true,
            trace: PipelineTrace::default(),
            from_ontology: false,
            outcome: ChatOutcome::Abstained {
                unresolved: Vec::new(),
            },
            why: None,
            definition_provenance: None,
        };
        assert!(
            check(&honest, &Expected::DeniesOrAbstains { known }).is_pass(),
            "an honest abstain naming no known concept as unknown must PASS"
        );
    }
}
