use pr4xis::category::Category;
use pr4xis::category::entity::Entity;
use pr4xis::category::relationship::Relationship;

// Provenance ontology — tracking the origin and history of knowledge.
//
// Grounded in W3C PROV-O (PROV Ontology, 2013):
//   https://www.w3.org/TR/prov-o/
//
// PROV-O defines three core concepts:
//   Entity — a thing (document, dataset, ontology, concept)
//   Activity — something that happens (a commit, a build, a derivation)
//   Agent — something that bears responsibility (a person, a tool, a process)
//
// Extended with version control concepts relevant to praxis:
//   Repository, Commit, Branch, Tag, Version — the lifecycle of knowledge artifacts
//
// This ontology lets praxis know WHERE each concept came from:
//   - Which paper defines it
//   - Which commit introduced it
//   - Which version of which spec
//   - Who authored the ontology
//
// References:
// - W3C PROV-O (2013) — https://www.w3.org/TR/prov-o/
// - W3C PROV-DM (2013) — https://www.w3.org/TR/prov-dm/

/// Core provenance concepts, aligned with W3C PROV-O.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ProvenanceConcept {
    // === PROV-O core (W3C §3.1) ===
    /// prov:Entity — a thing with provenance (an ontology, a document, a dataset).
    Artifact,
    /// prov:Activity — something that produces or transforms artifacts (a commit, a build).
    Activity,
    /// prov:Agent — bearer of responsibility (a person, a tool, a CI system).
    Agent,

    // === Version control ===
    /// A source code repository.
    Repository,
    /// A commit — an atomic change to a repository.
    Commit,
    /// A branch — a named line of development.
    Branch,
    /// A tag — a named point in history (e.g. v1.0).
    Tag,
    /// A version — a semantic version identifier.
    Version,

    // === Knowledge sources ===
    /// An academic paper or specification that defines concepts.
    Source,
    /// A specific section or definition within a source.
    Citation,
}

impl Entity for ProvenanceConcept {
    fn variants() -> Vec<Self> {
        vec![
            Self::Artifact,
            Self::Activity,
            Self::Agent,
            Self::Repository,
            Self::Commit,
            Self::Branch,
            Self::Tag,
            Self::Version,
            Self::Source,
            Self::Citation,
        ]
    }
}

/// Relationships between provenance concepts, aligned with W3C PROV-O.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ProvenanceRelation {
    pub from: ProvenanceConcept,
    pub to: ProvenanceConcept,
    pub kind: ProvenanceRelationKind,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ProvenanceRelationKind {
    Identity,
    /// prov:wasGeneratedBy — Artifact was generated by Activity.
    WasGeneratedBy,
    /// prov:wasDerivedFrom — Artifact was derived from another Artifact.
    WasDerivedFrom,
    /// prov:wasAttributedTo — Artifact was attributed to Agent.
    WasAttributedTo,
    /// prov:wasAssociatedWith — Activity was associated with Agent.
    WasAssociatedWith,
    /// prov:used — Activity used Artifact.
    Used,
    /// Commit belongs to Repository.
    BelongsTo,
    /// Branch points to Commit.
    PointsTo,
    /// Tag marks a Commit.
    Marks,
    /// Artifact is defined by Source (academic paper, spec).
    DefinedBy,
    /// Citation references a specific part of Source.
    References,
    /// Version identifies an Artifact.
    Identifies,
    Composed,
}

impl Relationship for ProvenanceRelation {
    type Object = ProvenanceConcept;
    fn source(&self) -> ProvenanceConcept {
        self.from
    }
    fn target(&self) -> ProvenanceConcept {
        self.to
    }
}

pub struct ProvenanceCategory;

impl Category for ProvenanceCategory {
    type Object = ProvenanceConcept;
    type Morphism = ProvenanceRelation;

    fn identity(obj: &ProvenanceConcept) -> ProvenanceRelation {
        ProvenanceRelation {
            from: *obj,
            to: *obj,
            kind: ProvenanceRelationKind::Identity,
        }
    }

    fn compose(f: &ProvenanceRelation, g: &ProvenanceRelation) -> Option<ProvenanceRelation> {
        if f.to != g.from {
            return None;
        }
        if f.kind == ProvenanceRelationKind::Identity {
            return Some(g.clone());
        }
        if g.kind == ProvenanceRelationKind::Identity {
            return Some(f.clone());
        }
        Some(ProvenanceRelation {
            from: f.from,
            to: g.to,
            kind: ProvenanceRelationKind::Composed,
        })
    }

    fn morphisms() -> Vec<ProvenanceRelation> {
        use ProvenanceConcept::*;
        use ProvenanceRelationKind::*;

        let mut m = Vec::new();

        // Identities
        for c in ProvenanceConcept::variants() {
            m.push(ProvenanceRelation {
                from: c,
                to: c,
                kind: Identity,
            });
        }

        // PROV-O core relations
        m.push(ProvenanceRelation {
            from: Artifact,
            to: Activity,
            kind: WasGeneratedBy,
        });
        m.push(ProvenanceRelation {
            from: Artifact,
            to: Artifact,
            kind: WasDerivedFrom,
        });
        m.push(ProvenanceRelation {
            from: Artifact,
            to: Agent,
            kind: WasAttributedTo,
        });
        m.push(ProvenanceRelation {
            from: Activity,
            to: Agent,
            kind: WasAssociatedWith,
        });
        m.push(ProvenanceRelation {
            from: Activity,
            to: Artifact,
            kind: Used,
        });

        // Version control
        m.push(ProvenanceRelation {
            from: Commit,
            to: Repository,
            kind: BelongsTo,
        });
        m.push(ProvenanceRelation {
            from: Branch,
            to: Commit,
            kind: PointsTo,
        });
        m.push(ProvenanceRelation {
            from: Tag,
            to: Commit,
            kind: Marks,
        });
        m.push(ProvenanceRelation {
            from: Version,
            to: Artifact,
            kind: Identifies,
        });

        // Knowledge sources
        m.push(ProvenanceRelation {
            from: Artifact,
            to: Source,
            kind: DefinedBy,
        });
        m.push(ProvenanceRelation {
            from: Citation,
            to: Source,
            kind: References,
        });

        // Transitive compositions
        m.push(ProvenanceRelation {
            from: Artifact,
            to: Agent,
            kind: Composed,
        });
        m.push(ProvenanceRelation {
            from: Activity,
            to: Artifact,
            kind: Composed,
        });
        m.push(ProvenanceRelation {
            from: Commit,
            to: Artifact,
            kind: Composed,
        });
        m.push(ProvenanceRelation {
            from: Branch,
            to: Repository,
            kind: Composed,
        });
        m.push(ProvenanceRelation {
            from: Tag,
            to: Repository,
            kind: Composed,
        });

        // Self-composed (closure)
        for c in ProvenanceConcept::variants() {
            m.push(ProvenanceRelation {
                from: c,
                to: c,
                kind: Composed,
            });
        }

        m
    }
}
