/// Formal sciences — abstract, timeless structures.
/// DOLCE: AbstractObject.
pub mod analytical_methods;
pub mod calculator;
pub mod causation;
pub mod classification;
pub mod derivation;
pub mod doctrine_discovery;
pub mod functor_synthesizer;
pub mod information;
pub mod logic;
pub mod math;
pub mod mereology;
pub mod meta;
pub mod optimization;
pub mod recommendation;
pub mod relations;
pub mod rule_algebra;
pub mod spatial;
pub mod systems;
