//! XSD-codegen'd XHTML 1.0 Strict ontology types.
//!
//! Generated by [`xsd-parser`] 1.5.2 from the W3C's XHTML 1.0
//! Strict XSD at build time, via
//! `pr4xis::codegen::xhtml_schema::generate_xhtml_schema_source`.
//! Per `feedback_bottom_up_loaded_not_encoded` — every Tier 2+
//! ontology type is LOADED from an authoritative source, never
//! hand-coded as Rust enum variants.
//!
//! [`xsd-parser`]: https://docs.rs/xsd-parser/1.5.2
//!
//! ## Citations
//!
//! - Pemberton, S. et al. (eds.) (2002) *XHTML 1.0: The Extensible
//!   HyperText Markup Language (Second Edition)*, W3C Recommendation
//!   1 August 2002, §A.1 Document Type Definitions
//!   (<https://www.w3.org/TR/xhtml1/#dtds>); the companion XSD at
//!   <https://www.w3.org/2002/08/xhtml/xhtml1-strict.xsd> is a
//!   faithful XML Schema rendering of the §A.1.1 Strict DTD.
//! - Gao, S., Sperberg-McQueen, C. M., and Thompson, H. S. (eds.)
//!   *W3C XML Schema Definition Language (XSD) 1.1 Part 1:
//!   Structures*, W3C Recommendation 5 April 2012.
//!   <https://www.w3.org/TR/xmlschema11-1/>.
//!
//! ## Usage
//!
//! The generated types are XSD-faithful: every `<xsd:element>`,
//! `<xsd:complexType>`, `<xsd:simpleType>`, `<xsd:attributeGroup>`,
//! and `<xsd:group>` from XHTML 1.0 Strict has a corresponding
//! Rust type. Type names follow xsd-parser's PascalCase convention;
//! complex types get an `Item` postfix (matching the USLM tree's
//! convention so the two generated namespaces are naming-
//! consistent).
//!
//! ## Build-time fallback
//!
//! If the XHTML XSD is not on disk (e.g. a fresh checkout where the
//! source hasn't been fetched) or xsd-parser fails to parse it, the
//! build script writes a commented stub instead of generated types.
//! This module then compiles to an empty module — downstream code
//! that references generated types will fail to link with a clear
//! `name not found` error.

#![allow(
    clippy::all,
    unused,
    missing_docs,
    dead_code,
    non_camel_case_types,
    non_snake_case
)]

include!(concat!(env!("OUT_DIR"), "/xhtml_schema_generated.rs"));
