//! HTML5 ontology — loaded from the XHTML 1.0 Strict XSD
//! (`xhtml_1_0_xsd@1.0`) with WHATWG HTML Living Standard content-
//! category semantics overlaid.
//!
//! ## Module layout
//!
//! - [`ontology`] — the HTML5 concept inventory + axioms
//!   (HtmlComponent / HtmlElement / HtmlAttribute /
//!   HtmlContentCategory + leaves). Closed enumeration of content
//!   categories per WHATWG HTML LS §3.2.5; element / attribute
//!   instances are loaded from the XSD at runtime.
//! - [`loader`] — runtime loader. Reads the bundled XHTML 1.0
//!   Strict XSD on first access (`include_str!`) and exposes
//!   `element_names()` / `attribute_names()` lazily cached sets,
//!   plus `is_html_element(name)` / `is_html_attribute(name)`
//!   case-insensitive lookups.
//! - [`english_projection`] — functor: every HTML element /
//!   attribute name projects through the English/WordNet pipeline;
//!   the bundled XSD's own naming acts as the authoritative answer
//!   for HTML-vocabulary tokens.
//! - [`generated`] — xsd-parser-emitted Rust types describing every
//!   `<xs:element>` / `<xs:complexType>` / `<xs:simpleType>` from
//!   the schema. Generated by
//!   `pr4xis::codegen::xhtml_schema::generate_xhtml_schema_source`
//!   at build time; written to `$OUT_DIR/xhtml_schema_generated.rs`.
//!
//! ## Citations
//!
//! - **Pemberton et al. (eds.) (2002)** *XHTML 1.0: The Extensible
//!   HyperText Markup Language (Second Edition)*, W3C Recommendation
//!   1 August 2002. <https://www.w3.org/TR/xhtml1/>. §A.2 XHTML
//!   1.0 Strict Schema.
//! - **WHATWG (current edition)** *HTML Living Standard*.
//!   <https://html.spec.whatwg.org/>. §3.2.5 Content models;
//!   §13.1.2 Tag-name case-insensitivity.
//! - **Raggett, Le Hors & Jacobs (eds.) (1999)** *HTML 4.01
//!   Specification*, W3C Recommendation 24 December 1999.
//!   <https://www.w3.org/TR/html4/>. §3.2.2 Element / attribute
//!   names case-insensitivity.

pub mod english_projection;
pub mod generated;
pub mod loader;
pub mod ontology;

#[cfg(test)]
mod tests;

pub use ontology::*;
