//! Sensor modality — backward-compatibility alias.
//!
//! The sensor taxonomy and its variant enum now live in
//! `super::ontology` (generated by the `pr4xis::ontology!` proc macro as
//! `SensorConcept`). This module re-exports it under its historical name
//! `SensorType` so that downstream consumers (`calibration.rs`,
//! `model.rs`, `observation/measurement.rs`, `time/clock.rs`,
//! `time/epoch.rs`, …) continue to compile without a sweeping rename.
//!
//! New code should prefer `SensorConcept` directly.

pub use super::ontology::SensorConcept as SensorType;
