//! XSD-codegen'd USLM ontology types.
//!
//! Generated by [`xsd-parser`] 1.5.2 from the LRC's
//! USLM-1.0.18.xsd at build time, via
//! `pr4xis::codegen::uslm_schema::generate_uslm_schema_source`.
//! Per `feedback_bottom_up_loaded_not_encoded` — every Tier 2+
//! ontology type is LOADED from an authoritative source, never
//! hand-coded as Rust enum variants.
//!
//! [`xsd-parser`]: https://docs.rs/xsd-parser/1.5.2
//!
//! ## Citations
//!
//! - U.S. House Office of the Law Revision Counsel, *USLM XML
//!   User Guide and Schema (USLM-1.0.18.xsd)*.
//!   <https://uscode.house.gov/uslm/>.
//! - Gao, S., Sperberg-McQueen, C. M., and Thompson, H. S. (eds.)
//!   *W3C XML Schema Definition Language (XSD) 1.1 Part 1:
//!   Structures*, W3C Recommendation 5 April 2012.
//!   <https://www.w3.org/TR/xmlschema11-1/>.
//!
//! ## Coexistence with hand-coded `uslm::corpus`
//!
//! This module coexists with the runtime-aggregate types in
//! [`super::corpus`][]. Field-level USLM types remain hand-coded
//! pending the upstream xsd-parser-types serde-derives PR; once
//! that lands the corpus aggregates will delegate to xsd-parser-
//! generated output and the duplication collapses.
//!
//! ## Usage
//!
//! The generated types are XSD-faithful: every `<xsd:element>`,
//! `<xsd:complexType>`, `<xsd:simpleType>`, `<xsd:attributeGroup>`,
//! and `<xsd:group>` from USLM-1.0.18.xsd has a corresponding
//! Rust type. Type names follow xsd-parser's PascalCase
//! convention; complex types get an `Item` postfix to avoid
//! collisions with xsd-parser's built-in aliases (e.g. USLM
//! `<complexType name="DateType">` → `DateTypeItem`).
//!
//! ```no_run
//! // The generated types live in this module's flat namespace.
//! use pr4xis_domains::social::software::markup::xml::uslm::generated;
//! // No constructor is exercised here — the types are XSD-shaped;
//! // a future "switch" commit wires the existing
//! // `uslm::lens::read_section` to populate them.
//! let _ = std::any::type_name::<generated::ActionTypeItem>();
//! ```
//!
//! ## Build-time fallback
//!
//! If the USLM XSD is not on disk (e.g. a fresh checkout where
//! `pr4xis update uslm_xsd` hasn't been run) or xsd-parser fails
//! to parse it, the build script writes a commented stub instead
//! of generated types. This module then compiles to an empty
//! module — downstream code that references generated types will
//! fail to link with a clear `name not found` error.

#![allow(
    clippy::all,
    unused,
    missing_docs,
    dead_code,
    non_camel_case_types,
    non_snake_case
)]

include!(concat!(env!("OUT_DIR"), "/uslm_schema_generated.rs"));

#[cfg(test)]
mod tests;
