//! Generates one `#[test]` per caregiver-corpus question into
//! `$OUT_DIR/generated_caregiver_questions.rs`, included by
//! `tests/caregiver_questions_generated.rs`.
//!
//! Reads ONLY the committed JSON fixture (question text, for the generated
//! function's name) — no question text is ever hand-typed in Rust. Each
//! generated test asserts its question is `"Green"` (honestly answerable);
//! the real classification logic
//! (`praxis_corpus_tests::caregiver::assert_is_green`) runs at TEST TIME,
//! not build time, so this script only needs `serde_json`, never the
//! (heavy) domains/chat crates.

use std::env;
use std::fs;
use std::path::Path;

fn slugify(question: &str, max_len: usize) -> String {
    let mut slug = String::new();
    let mut last_was_underscore = true; // suppress a leading underscore
    for ch in question.chars() {
        if ch.is_ascii_alphanumeric() {
            slug.push(ch.to_ascii_lowercase());
            last_was_underscore = false;
        } else if !last_was_underscore {
            slug.push('_');
            last_was_underscore = true;
        }
        if slug.len() >= max_len {
            break;
        }
    }
    while slug.ends_with('_') {
        slug.pop();
    }
    if slug.is_empty() {
        slug.push('q');
    }
    slug
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("set by cargo");
    let fixture_path =
        Path::new(&manifest_dir).join("tests/fixtures/caregiver_question_corpus.json");
    println!("cargo:rerun-if-changed={}", fixture_path.display());

    let fixture_raw = fs::read_to_string(&fixture_path).expect("read caregiver fixture");
    let fixture: Vec<serde_json::Value> =
        serde_json::from_str(&fixture_raw).expect("parse caregiver fixture as JSON array");

    let mut out = String::new();
    out.push_str("// GENERATED by build.rs from tests/fixtures/caregiver_question_corpus.json.\n");
    out.push_str(
        "// Do not edit. Each test asserts its question is Green (honestly answerable) —\n",
    );
    out.push_str("// a failure names a real, tracked capability gap, not a bug in the test.\n\n");

    let mut seen_names = std::collections::HashSet::new();
    for (index, entry) in fixture.iter().enumerate() {
        let question = entry
            .get("question")
            .and_then(|v| v.as_str())
            .unwrap_or_default();
        let slug = slugify(question, 48);
        let name = format!("q_{index:04}_{slug}");
        assert!(
            seen_names.insert(name.clone()),
            "generated test name collision at index {index}: {name}"
        );
        out.push_str(&format!(
            "#[test]\nfn {name}() {{\n    praxis_corpus_tests::caregiver::assert_is_green({index});\n}}\n\n"
        ));
    }

    let out_dir = env::var("OUT_DIR").expect("set by cargo");
    let dest = Path::new(&out_dir).join("generated_caregiver_questions.rs");
    fs::write(&dest, out).expect("write generated test file");

    generate_dialogue_tests(&manifest_dir, &out_dir);
    generate_adversarial_tests(&manifest_dir, &out_dir);
}

/// One `#[test]` PER authored multi-turn dialogue (task #18), from
/// `tests/fixtures/caregiver_dialogue_corpus.json` — unlike the question
/// corpus above, there is no companion snapshot: the fixture's
/// `expectedOutcome`/`expectedApplies` fields ARE the authored ground truth
/// (see `src/dialogue.rs`'s module docs for why).
fn generate_dialogue_tests(manifest_dir: &str, out_dir: &str) {
    let fixture_path =
        Path::new(manifest_dir).join("tests/fixtures/caregiver_dialogue_corpus.json");
    println!("cargo:rerun-if-changed={}", fixture_path.display());

    let fixture_raw = fs::read_to_string(&fixture_path).expect("read dialogue fixture");
    let fixture: Vec<serde_json::Value> =
        serde_json::from_str(&fixture_raw).expect("parse dialogue fixture as JSON array");

    let mut out = String::new();
    out.push_str("// GENERATED by build.rs from tests/fixtures/caregiver_dialogue_corpus.json.\n");
    out.push_str("// Do not edit.\n\n");

    let mut seen_names = std::collections::HashSet::new();
    for (index, entry) in fixture.iter().enumerate() {
        let dialogue_name = entry
            .get("name")
            .and_then(|v| v.as_str())
            .unwrap_or_default();
        let slug = slugify(dialogue_name, 60);
        let name = format!("d_{index:02}_{slug}");
        assert!(
            seen_names.insert(name.clone()),
            "generated dialogue test name collision at index {index}: {name}"
        );
        out.push_str(&format!(
            "#[test]\nfn {name}() {{\n    praxis_corpus_tests::dialogue::assert_dialogue_matches_fixture({index});\n}}\n\n"
        ));
    }

    let dest = Path::new(out_dir).join("generated_caregiver_dialogues.rs");
    fs::write(&dest, out).expect("write generated dialogue test file");
}

/// One `#[test]` PER adversarial honesty question (task #15/#37), from
/// `tests/fixtures/adversarial_question_corpus.json` + its companion
/// `adversarial_question_corpus.snapshot.json` — a snapshot-comparison
/// assertion, deliberately NOT the caregiver-question codegen's bare
/// "must be Green" shape above: a safe outcome here isn't a single target
/// value the way "honestly answerable" is, so the meaningful signal is a
/// CHANGE in outcome kind (a lateral shift between unsafe-outcome
/// categories fails loud too), not a fixed pass/fail target. See
/// `src/adversarial.rs`'s module docs.
fn generate_adversarial_tests(manifest_dir: &str, out_dir: &str) {
    let fixture_path =
        Path::new(manifest_dir).join("tests/fixtures/adversarial_question_corpus.json");
    let snapshot_path =
        Path::new(manifest_dir).join("tests/fixtures/adversarial_question_corpus.snapshot.json");
    println!("cargo:rerun-if-changed={}", fixture_path.display());
    println!("cargo:rerun-if-changed={}", snapshot_path.display());

    let fixture_raw = fs::read_to_string(&fixture_path).expect("read adversarial fixture");
    let fixture: Vec<serde_json::Value> =
        serde_json::from_str(&fixture_raw).expect("parse adversarial fixture as JSON array");
    let snapshot_raw = fs::read_to_string(&snapshot_path).expect("read adversarial snapshot");
    let snapshot: Vec<String> = serde_json::from_str(&snapshot_raw)
        .expect("parse adversarial snapshot as JSON string array");

    assert_eq!(
        fixture.len(),
        snapshot.len(),
        "adversarial_question_corpus.json has {} entries but its snapshot has {} — \
         regenerate the snapshot (see tests/adversarial_questions_generated.rs)",
        fixture.len(),
        snapshot.len()
    );

    let mut out = String::new();
    out.push_str("// GENERATED by build.rs from tests/fixtures/adversarial_question_corpus.json\n");
    out.push_str("// + tests/fixtures/adversarial_question_corpus.snapshot.json. Do not edit.\n\n");

    let mut seen_names = std::collections::HashSet::new();
    for (index, entry) in fixture.iter().enumerate() {
        let question = entry
            .get("question")
            .and_then(|v| v.as_str())
            .unwrap_or_default();
        let category = entry
            .get("category")
            .and_then(|v| v.as_str())
            .unwrap_or_default();
        let slug = slugify(&format!("{category}_{question}"), 56);
        let name = format!("a_{index:04}_{slug}");
        assert!(
            seen_names.insert(name.clone()),
            "generated adversarial test name collision at index {index}: {name}"
        );
        let expected = &snapshot[index];
        out.push_str(&format!(
            "#[test]\nfn {name}() {{\n    praxis_corpus_tests::adversarial::assert_matches_snapshot({index}, {expected:?});\n}}\n\n"
        ));
    }

    let dest = Path::new(out_dir).join("generated_adversarial_questions.rs");
    fs::write(&dest, out).expect("write generated adversarial test file");
}
