//! `OwlGraphFaithfulLens` — the byte-exact graph-faithful [`WellBehavedLens`]
//! for an OWL/RDF source, and the registration that flips `cito` off the
//! universal floor in the completeness meter.
//!
//! # The first graph-faithful OWL vocabulary
//!
//! The five other bundled OWL vocabularies (doco, c4o, biro, prov_o, olia) ride
//! the universal FLOOR ([`RoundTripFidelity::RawBytesComplementFloor`], the
//! [`OwlLens`](super::lens::OwlLens) constant-complement identity) — byte-exact
//! only via a stored raw-bytes complement. **CiTO is praxis's FIRST OWL source
//! held to the strict byte-exact PutGet law** ([`RoundTripFidelity::ByteExactGraphFaithful`],
//! Foster, Greenwald, Moore, Pierce & Schmitt 2007 §2.2): the source regenerates
//! from the typed [`OwlOntology`] graph PLUS a content-addressed concrete-syntax
//! complement ([`OwlSyntaxComplement`] — the structured RDF/XML striping + the
//! generic DOCTYPE/namespace/white-space/attribute/entity/EOL residue), with NO
//! stored raw blob.
//!
//! It is the OWL sibling of the WN-LMF [`WordNetLmfLens`] and the USLM
//! `UslmGraphFaithfulLens`:
//!
//! - **`get : &[u8] → OwlGraphFaithfulView`** — [`capture_owl_complement`]:
//!   parse the source, project the typed OWL graph AND the byte-affecting
//!   residue. Fails closed on malformed input, a non-flat RDF/XML
//!   serialization, or a structural-writer backbone divergence.
//! - **`put : &OwlGraphFaithfulView → Vec<u8>`** —
//!   [`reconstruct_owl_rdfxml_source`]: regenerate the element backbone from the
//!   structured striping, re-apply the complement, serialize byte-exact.
//! - **`canonical`** — the IDENTITY: a byte-exact lens's source IS its own
//!   canonical form (`put(get(b)) == b`), so there is no separate canonical
//!   normalization; the byte-exact harness path never calls it (it compares raw
//!   bytes via `assert_byte_exact_law` and signs the raw bytes,
//!   `[byte_exact_signatures]`). Provided only for trait totality.
//!
//! # What registering this lens does
//!
//! The completeness meter reads each source's DECLARED fidelity from its
//! registered lens's [`WellBehavedLens::FIDELITY`]. Registering
//! `OwlGraphFaithfulLens` for `cito@2.8.1` (replacing the floor `OwlLens`
//! registration) with `FIDELITY = ByteExactGraphFaithful` declares CiTO
//! graph-faithful; the harness MEASURES the achieved tier by running the
//! byte-exact law against the `[byte_exact_signatures]` pin (which, because
//! `put(get(b)) == b`, equals the raw-source `[hashes]` pin). The OTHER FIVE OWL
//! vocabularies keep the floor `OwlLens` registration unchanged.
//!
//! # The RDFC-1.0 graph-identity gate is untouched
//!
//! This is the **byte-exact** law (raw-bytes round-trip). The separate
//! RDFC-1.0 graph-identity gate ([`OwlLens::canonical`](super::lens::OwlLens) /
//! `[canonical_signatures]`, the load-gate canonical leg) is unchanged: the
//! `.prx` load path still re-derives the canonical N-Quads of CiTO's source
//! graph and checks them against `[canonical_signatures]`. The two laws bind
//! different identities and run independently.
//!
//! # Citations
//!
//! - **Foster, Greenwald, Moore, Pierce & Schmitt (2007)** *ACM TOPLAS* 29(3)
//!   §2.2 — the strict byte-exact PutGet law.
//! - **Gandon & Schreiber (2014)** *RDF 1.1 XML Syntax* — the RDF/XML
//!   serialization the structured striping projects.
//!
//! [`OwlOntology`]: super::ontology::OwlOntology
//! [`WordNetLmfLens`]: crate::social::software::markup::xml::lmf::lens::WordNetLmfLens

#[allow(unused_imports)]
use alloc::{format, string::String, vec::Vec};

use super::ontology::OwlOntology;
use super::rdfxml_writer::{
    OwlReconstructError, OwlSyntaxComplement, capture_owl_complement, reconstruct_owl_rdfxml_source,
};
use crate::formal::meta::well_behaved_lens::{RoundTripFidelity, WellBehavedLens};

/// The OWL/RDF byte-exact graph-faithful lens: `bytes ↔ (OWL ontology +
/// structured RDF/XML complement)`. The first praxis OWL lens declaring
/// [`RoundTripFidelity::ByteExactGraphFaithful`].
#[derive(Debug)]
pub struct OwlGraphFaithfulLens;

/// The graph-faithful target: the typed [`OwlOntology`] graph paired with the
/// concrete-syntax [`OwlSyntaxComplement`] the byte-exact `put` re-applies.
/// `get` produces this pair; `put` consumes it to regenerate the source bytes.
///
/// No `PartialEq`/`Eq` derive — [`OwlOntology`] is not `Eq` (it carries the
/// proof/category machinery), and the [`WellBehavedLens`] trait places no
/// bounds on `Target`. The byte-exact law compares the regenerated BYTES, not
/// the view value.
#[derive(Debug, Clone)]
pub struct OwlGraphFaithfulView {
    /// The typed OWL ontology — the navigable reasoning graph.
    pub ontology: OwlOntology,
    /// The concrete-syntax residue the typed ontology does not carry (the
    /// RDF/XML striping + the generic DOCTYPE/namespace/white-space/attribute
    /// residue).
    pub complement: OwlSyntaxComplement,
}

/// Error from the OWL graph-faithful lens: a UTF-8 decode failure or an
/// [`OwlReconstructError`] from the capture/reconstruct pair.
#[derive(Debug)]
pub enum OwlGraphFaithfulLensError {
    /// The source bytes are not valid UTF-8 (OWL/RDF is XML text).
    NotUtf8(String),
    /// The graph-faithful capture or reconstruction failed.
    Reconstruct(OwlReconstructError),
}

impl core::fmt::Display for OwlGraphFaithfulLensError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::NotUtf8(e) => write!(f, "OWL/RDF source is not UTF-8: {e}"),
            Self::Reconstruct(e) => write!(f, "OWL/RDF graph-faithful round-trip: {e}"),
        }
    }
}

impl std::error::Error for OwlGraphFaithfulLensError {}

impl From<OwlReconstructError> for OwlGraphFaithfulLensError {
    fn from(e: OwlReconstructError) -> Self {
        Self::Reconstruct(e)
    }
}

impl WellBehavedLens for OwlGraphFaithfulLens {
    type Target = OwlGraphFaithfulView;
    type Error = OwlGraphFaithfulLensError;

    /// CiTO's tier — held to the strict byte-exact PutGet law.
    const FIDELITY: RoundTripFidelity = RoundTripFidelity::ByteExactGraphFaithful;

    /// `get` — capture the typed graph AND the concrete-syntax complement from
    /// the source ([`capture_owl_complement`]).
    fn get(bytes: &[u8]) -> Result<Self::Target, Self::Error> {
        let text = core::str::from_utf8(bytes)
            .map_err(|e| OwlGraphFaithfulLensError::NotUtf8(format!("{e}")))?;
        // Strip an optional BOM (W3C XML 1.0 §F.1), as OwlLens::get does.
        let text = text.strip_prefix('\u{feff}').unwrap_or(text);
        let (ontology, complement) = capture_owl_complement(text)?;
        Ok(OwlGraphFaithfulView {
            ontology,
            complement,
        })
    }

    /// `put` — regenerate the source bytes from the structured complement
    /// ([`reconstruct_owl_rdfxml_source`]), NO stored raw blob.
    fn put(target: &Self::Target) -> Result<Vec<u8>, Self::Error> {
        Ok(reconstruct_owl_rdfxml_source(&target.complement)?)
    }

    /// `canonical` — the IDENTITY for a byte-exact lens: the source is its own
    /// canonical form (`put(get(b)) == b`). The byte-exact harness path never
    /// calls this; it is here only for trait totality.
    fn canonical(bytes: &[u8]) -> Result<Vec<u8>, Self::Error> {
        Ok(bytes.to_vec())
    }
}

// =============================================================================
// Harness registration — flips `cito` to graph-faithful.
//
// Binds `OwlGraphFaithfulLens` to `cito@2.8.1`, REPLACING its floor `OwlLens`
// registration (the other five OWL vocabs keep `OwlLens`). The harness runs the
// byte-exact law (because FIDELITY is ByteExactGraphFaithful) and verifies the
// raw-bytes signature against `[byte_exact_signatures]` in praxis.lock. Native
// only — linkme's distributed slice is unsupported on wasm32, mirroring every
// other `register_lens!`.
// =============================================================================

crate::register_lens!(
    CITO_GRAPH_FAITHFUL_LENS,
    "cito",
    "2.8.1",
    OwlGraphFaithfulLens
);

#[cfg(test)]
mod tests {
    use super::*;

    /// The lens's byte-exact PutGet law holds on the REAL bundled CiTO:
    /// `put(get(b)) == b` byte-for-byte — the law the harness runs for `cito`.
    #[test]
    fn owl_graph_faithful_lens_is_byte_exact_on_cito() {
        let bytes = std::fs::read(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/data/ontologies/cito-2.8.1.owl"
        ))
        .expect("bundled CiTO must exist");
        OwlGraphFaithfulLens::assert_byte_exact_law(&bytes)
            .expect("OWL graph-faithful lens must satisfy the byte-exact PutGet law on CiTO");
    }

    /// The lens declares the graph-faithful tier — the const the completeness
    /// meter reads to flip `cito` off the floor.
    #[test]
    fn owl_graph_faithful_lens_declares_graph_faithful() {
        assert_eq!(
            OwlGraphFaithfulLens::FIDELITY,
            RoundTripFidelity::ByteExactGraphFaithful,
            "CiTO is praxis's first graph-faithful OWL source"
        );
    }

    /// `canonical` is the identity (a byte-exact lens's source is its own
    /// canonical form) — provided only for trait totality.
    #[test]
    fn owl_graph_faithful_canonical_is_identity() {
        let sample = b"<x/>";
        let c = OwlGraphFaithfulLens::canonical(sample).expect("canonical");
        assert_eq!(c, sample, "byte-exact lens canonical is identity");
    }
}
