//! The LOADED-LEXICON chat-capability suite — registry-driven over the
//! definitional chat-lexicon kinds, at full-WordNet scale, with a
//! ZERO-DEFECT bar.
//!
//! The corpus lane (`chat_capability.rs`) ratchets defect ceilings over the
//! 100k-synset English ⊕ USC universe, where residual defect classes are
//! tracked down monotonically. The registered definitional lexicons are
//! different: they are AUTHORED — every synset carries exactly one cited
//! gloss and a verified isA taxonomy — so the bar is zero, not a ratchet.
//! Every case is generated by the SAME generic machinery the corpus lane
//! uses (`pr4xis_chat::capability::{Frames, probe_cases, run_case}`): the
//! generator walks a `ComposedReasoner` over sample English ⊕ the loaded
//! lexicons (a full witness walk, so EVERY lexicon concept and EVERY
//! hypernym-closure pair is enumerated — the corpus lane's strided budget
//! would drown the ~10²-concept lexicon stratum in the 10⁵-concept English
//! id space), the emitted cases are filtered to LEXICON provenance
//! (`Construct` ids decode through `ontology_of_concept`), and each case
//! RUNS against the production composition `ComposedReasoner::new(
//! english_loaded(), lexicons)` — full WordNet resident, exactly what the
//! CLI/wasm chat hosts assemble. Questions and expected properties are
//! strings realized from the lexicons' own labels/glosses, identical under
//! both reasoners, so the generation walk never leaks into the verdict.
//!
//! Registry-driven throughout: the lexicon set is
//! `data_sources()` filtered through the kind-keyed residency dispatch
//! (`chat_lexicons::definitional_lexicon_runtime_ontology`) — no lexicon is
//! named in this file, and registering a new definitional lexicon extends
//! the suite with zero edits here.

use std::rc::Rc;

use pr4xis_chat::capability::{Construct, Frames, SampleBudget, probe_cases, run_case};
use pr4xis_chat::{ChatOutcome, process_with_reasoner};
use pr4xis_domains::applied::data_provisioning::chat_lexicons::definitional_lexicon_runtime_ontology;
use pr4xis_domains::applied::data_provisioning::registry::data_sources;
use pr4xis_domains::cognitive::linguistics::composed::ComposedReasoner;
use pr4xis_domains::cognitive::linguistics::english::bridge::{CONCEPT_KIND, SUBSUMPTION_REL};
use pr4xis_domains::cognitive::linguistics::english::{English, LexicalReasoner, english_loaded};
use pr4xis_runtime::ontology::RuntimeOntology;
use praxis_corpus_tests::{load_wordnet_corpus, require};

/// A registered seed for the deterministic sampler — identical run-to-run.
const LEXICON_SEED: u64 = 0x1E71_C0DE_2026_0714;

/// Every registered definitional chat lexicon, materialized through the
/// registry-driven residency dispatch — the SAME selection the CLI runs at
/// startup. Panics if the registry carries none (the suite must never be
/// vacuously green) or if any registered lexicon fails to materialize.
fn registered_lexicons() -> Vec<Rc<RuntimeOntology>> {
    let mut out = Vec::new();
    for entry in data_sources() {
        let Some(result) = definitional_lexicon_runtime_ontology(entry) else {
            continue;
        };
        let onto = result
            .unwrap_or_else(|e| panic!("registered lexicon {} must materialize: {e}", entry.name));
        out.push(Rc::new(onto));
    }
    assert!(
        !out.is_empty(),
        "the registry must carry at least one definitional chat lexicon"
    );
    out
}

/// The full-WordNet English substrate, provisioned-or-HARD-FAIL (tests do
/// not skip; a bare checkout is told to run `pr4xis update english_wordnet`).
fn corpus_english() -> &'static English {
    let wn = load_wordnet_corpus();
    require(wn.english(), "english_wordnet");
    english_loaded()
}

/// THE ZERO-DEFECT GATE: every lexicon concept's "what is X" answer carries
/// its cited gloss, and every hypernym-closure pair "is X a Y" affirms —
/// over the production composition (full WordNet ⊕ the registered
/// lexicons), with NO ratchet: the lexicons are authored, so one defect is
/// a defect.
#[pr4xis::praxis_value(Verifiable)]
#[test]
fn every_lexicon_gloss_defines_and_every_hypernym_edge_affirms() {
    let lexicons = registered_lexicons();
    let english = corpus_english();

    // The GENERATION walk: sample English ⊕ the lexicons — small enough for
    // the witness budget's exhaustive stride, so every lexicon concept and
    // every closure pair emits a case. (Questions/expectations are label and
    // gloss STRINGS from the lexicons' own archives — identical under the
    // production reasoner below.)
    let generator = ComposedReasoner::new(English::sample_static(), lexicons.clone());
    // The ANSWERING composition: what the CLI/wasm hosts actually run.
    let production = ComposedReasoner::new(english, lexicons.clone());
    let frames = Frames::from_realization();

    // The suite's own floor, derived from the loaded archives (never a
    // hand-pinned count): one define case per lexicon Concept node, and at
    // least one is-a case per Subsumption edge (the closure walk is a
    // superset of the direct edges).
    let mut concept_floor = 0usize;
    let mut edge_floor = 0usize;
    for onto in &lexicons {
        let archive = onto
            .to_owned_archive()
            .expect("a materialized lexicon archive round-trips");
        for node in &archive.nodes {
            if node.kind == CONCEPT_KIND {
                concept_floor += 1;
                edge_floor += node
                    .edges
                    .iter()
                    .filter(|(kind, _)| kind == SUBSUMPTION_REL)
                    .count();
            }
        }
    }

    let mut n_define = 0usize;
    let mut n_isa = 0usize;
    let mut failures: Vec<String> = Vec::new();
    for case in probe_cases(&generator, &frames, SampleBudget::witness(LEXICON_SEED)) {
        // Filter to LEXICON provenance: only the loaded ontologies' concepts
        // (English substrate ids decode to None). Directional-No and
        // non-edge run in the corpus lane; the authored-lexicon bar is
        // define + affirm (+ the abstention gate below).
        match case.construct {
            Construct::Definition { id, ref source } => {
                if source.is_none() || generator.ontology_of_concept(id).is_none() {
                    continue;
                }
                n_define += 1;
            }
            Construct::IsAPositive { child, ancestor } => {
                if generator.ontology_of_concept(child).is_none()
                    || generator.ontology_of_concept(ancestor).is_none()
                {
                    continue;
                }
                n_isa += 1;
            }
            _ => continue,
        }
        if let pr4xis_chat::capability::Verdict::Fail(why) = run_case(english, &production, &case) {
            failures.push(format!(
                "[{}] {:?} — {why}",
                case.construct.class_name(),
                case.question
            ));
        }
    }

    eprintln!(
        "LEXICON CHAT CAPABILITY: {n_define} define cases (floor {concept_floor}), \
         {n_isa} is-a cases (floor {edge_floor}), {} failures",
        failures.len()
    );
    assert_eq!(
        n_define, concept_floor,
        "every lexicon Concept must emit exactly one define case"
    );
    assert!(
        n_isa >= edge_floor,
        "the is-a walk must cover at least every direct Subsumption edge \
         (got {n_isa}, floor {edge_floor})"
    );
    assert!(
        failures.is_empty(),
        "ZERO-DEFECT bar: the authored lexicons admit no ratchet — {} failing cases:\n{}",
        failures.len(),
        failures.join("\n"),
    );
}

/// THE HONESTY GATE: a surface absent from EVERY loaded source (WordNet,
/// the lexicons) abstains — the turn is `Abstained` naming the unknown
/// surface, never an `Answered` fabrication (Reiter 1978 closed-world: an
/// abstention names only genuinely-unknown surfaces).
#[pr4xis::praxis_value(Honest)]
#[test]
fn a_known_absent_surface_abstains_without_fabricating() {
    let english = corpus_english();
    let production = ComposedReasoner::new(english, registered_lexicons());

    let unknown = "flurbogast";
    assert!(
        production.lookup(unknown).is_empty(),
        "the probe surface must be genuinely absent from every loaded source"
    );
    let result = process_with_reasoner(english, &production, &format!("what is {unknown}"));
    match &result.outcome {
        ChatOutcome::Abstained { unresolved } => {
            assert!(
                unresolved.iter().any(|u| u == unknown),
                "the abstention must name the genuinely-unknown surface; got {unresolved:?}"
            );
        }
        ChatOutcome::Answered => panic!(
            "a known-absent surface must abstain, not fabricate: {:?}",
            result.response
        ),
        ChatOutcome::Conditional { .. } => panic!(
            "a known-absent surface must abstain, not resolve to a rule: {:?}",
            result.response
        ),
        ChatOutcome::RuleResolved { .. } => panic!(
            "a single turn through process_with_reasoner never resolves a rule: {:?}",
            result.response
        ),
    }
}
