//! U.S. Code Title 1 graph-faithful `.prx` round-trip over the REAL corpus — the
//! USC twin of `wordnet.rs`'s `wordnet_graph_faithful_prx_round_trip_over_real_corpus`,
//! lifted out of the `pr4xis-domains` `#[cfg(test)]` modules.
//!
//! The literal on-disk Title 1 USLM source emits as a graph-faithful envelope,
//! serializes to rkyv, decodes through the bytecheck-validated gate, reconstructs
//! from the typed ontology + concrete-syntax complement (NO raw blob), and the
//! regenerated bytes equal the source BYTE-FOR-BYTE. The full
//! serialize → bytecheck → reconstruct path over the real corpus is heavy, so it
//! runs here in the one-process heavy-corpus lane rather than under the strict
//! fast-lane per-test cap. The cheap in-memory cousin
//! (`usc_title1_graph_faithful_reconstructs_source_byte_exact`) stays in-crate.
//!
//! USC titles are externally provisioned (`pr4xis update`); CI provisions them,
//! so a plain checkout that hasn't provisioned Title 1 HARD-FAILS via `require`
//! naming `pr4xis update usc_title_1` — tests do not skip.

use pr4xis_domains::formal::meta::well_behaved_lens::{
    CompletenessReport, DecompileKind, RoundTripFidelity as Tier, completeness_meter,
};
use pr4xis_domains::social::software::markup::xml::uslm::corpus::prx::{
    build_usc_envelope, usc_envelope_from_bytes, usc_envelope_to_bytes, usc_reconstruct_source,
};
use pr4xis_runtime::address::ContentAddress;

use praxis_corpus_tests::{require, workspace_root};

/// The registry `(name, version)` of the PROVEN graph-faithful title.
const T1_NAME: &str = "usc_title_1";
const T1_VERSION: &str = "pl-119-90";
const T1_URL: &str =
    "https://uscode.house.gov/download/releasepoints/us/pl/119/90/xml_usc01@119-90.zip";

/// The LITERAL on-disk Title 1 USLM file — the raw published bytes EXACTLY, CRLFs
/// included. `None` when the corpus is not provisioned; the caller routes that
/// `None` through [`require`] to HARD-FAIL (tests do not skip).
fn real_title1_source() -> Option<Vec<u8>> {
    let path = workspace_root()
        .join("crates/domains/data/legal/uscode/usc_title_1/usc_title_1-pl-119-90.xml");
    std::fs::read(&path).ok()
}

/// THE SLICE-U6 HARD GATE. The LITERAL on-disk `usc_title_1-pl-119-90.xml` (CRLFs
/// included) emits as a `ByteExactGraphFaithful` envelope, serializes to rkyv
/// bytes, loads back THROUGH the bytecheck-validated rkyv decode
/// (`usc_envelope_from_bytes`), reconstructs via `usc_reconstruct_source` (the
/// graph-faithful arm — typed `UsCodeTitle` ontology + concrete-syntax
/// complement, NO stored raw blob), and the regenerated bytes equal the source
/// BYTE-FOR-BYTE. This is the only non-vacuous proof that `usc_title_1`'s `.prx`
/// is graph-faithful end-to-end: the source bytes survive the FULL
/// serialize → bytecheck → reconstruct path, not just the in-memory
/// capture/reconstruct of slices U1–U5.
///
/// AND the completeness meter reports THIS title (`usc_title_1`, the test's own
/// subject) graph-faithful: its declared tier is `ByteExactGraphFaithful` via the
/// registered `UslmGraphFaithfulLens`, and it carries NO `write_uslm` gap.
#[test]
fn usc_title1_graph_faithful_prx_round_trip_over_real_corpus() {
    let source = require(real_title1_source(), "usc_title_1");

    // Emit the graph-faithful envelope: typed ontology + concrete-syntax
    // complement, NO raw blob.
    let envelope = build_usc_envelope(&source, T1_NAME, T1_VERSION, T1_URL)
        .expect("build graph-faithful envelope over the literal Title 1 source");
    assert_eq!(
        envelope.mode,
        Tier::ByteExactGraphFaithful,
        "the literal Title 1 source emits the graph-faithful tier"
    );
    assert!(envelope.graph.is_some(), "graph payload present");
    assert!(envelope.raw.is_none(), "NO stored raw blob in this tier");

    // Serialize → rkyv bytes → bytecheck-validated decode (the full path, not
    // just the in-memory capture/reconstruct of slices U1–U5).
    let rkyv_bytes = usc_envelope_to_bytes(&envelope).expect("serialize envelope to rkyv");
    let decoded = usc_envelope_from_bytes(&rkyv_bytes).expect("bytecheck-validated rkyv decode");

    // Reconstruct from the DECODED envelope's graph + complement.
    let out = usc_reconstruct_source(&decoded).expect("graph-faithful reconstruct");

    // BYTE-FOR-BYTE over the whole literal file. Report the EXACT first byte-diff
    // for an honest failure (a bounded 80-byte window).
    if out != source {
        let first = out
            .iter()
            .zip(source.iter())
            .position(|(a, b)| a != b)
            .unwrap_or(out.len().min(source.len()));
        let lo = first.saturating_sub(40);
        let hi_out = (first + 40).min(out.len());
        let hi_src = (first + 40).min(source.len());
        panic!(
            "graph-faithful .prx round-trip is NOT byte-exact: out.len()={}, \
             source.len()={}, first diff at byte {first}\n  out[..]: {:?}\n  src[..]: {:?}",
            out.len(),
            source.len(),
            String::from_utf8_lossy(&out[lo..hi_out]),
            String::from_utf8_lossy(&source[lo..hi_src]),
        );
    }
    assert_eq!(
        ContentAddress::of(&out).to_hex(),
        decoded.metadata.source_address,
        "the regenerated bytes must hash to the pinned source content address"
    );

    // The completeness meter reports usc_title_1 graph-faithful: declared tier ==
    // ByteExactGraphFaithful and NO write_uslm gap remains.
    let meter = completeness_meter();
    let t1_row: &CompletenessReport = meter
        .iter()
        .find(|r| r.source == "usc_title_1@pl-119-90")
        .expect("usc_title_1 must have a completeness row");
    assert_eq!(
        t1_row.kind,
        DecompileKind::UsCode,
        "usc_title_1 routes through the USC decompile leaf"
    );
    assert_eq!(
        t1_row.declared,
        Tier::ByteExactGraphFaithful,
        "usc_title_1 DECLARES graph-faithful (via the registered UslmGraphFaithfulLens)"
    );
    assert!(
        t1_row.graph_faithful_gap.is_none(),
        "usc_title_1 carries NO write_uslm gap — it IS graph-faithful, got gap {:?}",
        t1_row.graph_faithful_gap
    );
    // With the title provisioned the harness MEASURES the achieved tier by running
    // the byte-exact law; it must agree with the declaration (the anti-lie
    // cross-check), never silently fall to the floor.
    assert_eq!(
        t1_row.achieved,
        Some(Tier::ByteExactGraphFaithful),
        "with the title on disk the harness must MEASURE graph-faithful (achieved == declared)"
    );
    // Every OTHER title's declared tier is the source-agnostic concern of the
    // `prx_source_round_trip` meta-tests (registry-derived, no title named); this
    // focused test deliberately asserts only its own subject.
}
